In [174]:
import pandas as pd
import numpy as np

In [175]:
df = pd.read_csv('../data/raw/timber_felling_dataset.csv', sep=';')

ParserError: Error tokenizing data. C error: Expected 14 fields in line 15, saw 15

In [176]:
df.head()

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean
0,1748-1749,Benahú,Dehesa de Benahú,"36,57689304","-5,509202381",Jeréz de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,622,622.0,36.576893,-5.509202,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak
1,1748-1749,Jarda,Dehesa de la Jarda,"36,60223799","-5,6019132409",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,230,230.0,36.602238,-5.601913,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak
2,1748-1749,Barranco de la Fantasma,La Fantasma,"36,6099778174","-5,4648038479",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,240,240.0,36.609978,-5.464804,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak
3,1748-1749,La Jardilla,La Jardilla,"36,62178904","-5,518366056",Jeréz de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,1457,1457.0,36.621789,-5.518366,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak
4,1748-1749,Garganta de Millán,Millán,"36,61617144","-5,474945207",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,250,250.0,36.616171,-5.474945,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak

In [177]:
df.shape

(419, 19)

In [178]:
df.columns

Index(['felling_period', 'felling_toponymy_source', 'felling_toponymy_MTN25',
       'felling_latitude_WGS84', 'felling_longitude_WGS84', 'municipality',
       'province', 'landowner_type', 'landowner_name', 'tree_species',
       'tree_quantity', 'tree_quantity_clean', 'latitude_clean',
       'longitude_clean', 'province_clean', 'municipality_clean',
       'landowner_type_clean', 'landowner_name_clean', 'tree_species_clean'],
      dtype='str')

In [179]:
# remove empty columns imported by mistake
df = df.drop(columns=['Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'])

# check the columns again
df.columns

KeyError: "['Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'] not found in axis"

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 419 entries, 0 to 418
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   felling_period           419 non-null    str
 1   felling_toponymy_source  419 non-null    str
 2   felling_toponymy_MTN25   397 non-null    str
 3   felling_latitude_WGS84   221 non-null    str
 4   felling_longitude_WGS84  221 non-null    str
 5   municipality             419 non-null    str
 6   province                 419 non-null    str
 7   landowner_type           399 non-null    str
 8   landowner_name           394 non-null    str
 9   tree_species             401 non-null    str
 10  tree_quantity            404 non-null    str
dtypes: str(11)
memory usage: 77.1 KB

In [ ]:
# check missing values in each column
df.isna().sum()

felling_period               0
felling_toponymy_source      0
felling_toponymy_MTN25      22
felling_latitude_WGS84     198
felling_longitude_WGS84    198
municipality                 0
province                     0
landowner_type              20
landowner_name              25
tree_species                18
tree_quantity               15
tree_quantity_clean         15
latitude_clean             198
longitude_clean            198
province_clean               0
municipality_clean           0
landowner_type_clean        20
landowner_name_clean        25
tree_species_clean          18
dtype: int64

In [ ]:
# calculate the percentage of missing values
(df.isna().sum() / len(df) * 100).round(2)

felling_period              0.00
felling_toponymy_source     0.00
felling_toponymy_MTN25      5.25
felling_latitude_WGS84     47.26
felling_longitude_WGS84    47.26
municipality                0.00
province                    0.00
landowner_type              4.77
landowner_name              5.97
tree_species                4.30
tree_quantity               3.58
dtype: float64

In [ ]:
# inspect unique values from tree_quantity
df['tree_quantity'].dropna().unique()[:30]

<ArrowStringArray>
[        '622',         '230',         '240',        '1457',         '250',
         '383',         '384',         '360',         '370',         '213',
        '1406',        '2986',        '1300',         '320',         '533',
         '204',        '4198',   '898 trees', '1 645 trees',  '3150 trees',
    '91 trees',         '245',         '560', '3 593 trees',          '18',
   '102 trees',   '266 trees', '2 087 trees',   '186 trees',    '57 trees']
Length: 30, dtype: str

In [ ]:
# inspect the most common values in tree_quantity
df['tree_quantity'].value_counts().head(20)

tree_quantity
1            39
2            33
6            11
4            11
5            10
3            10
14            9
7             9
12            9
8             6
17            6
370           5
448           5
9             5
10            5
40            5
11            5
204           4
18            4
40  trees     4
Name: count, dtype: int64

In [ ]:
# clean tree_quantity values
df['tree_quantity_clean'] = (
    df['tree_quantity']
    .str.replace('trees', '', regex=False)
    .str.replace('tree', '', regex=False)
    .str.replace(' ', '', regex=False)
    .str.strip()
)

# convert to numeric
df['tree_quantity_clean'] = pd.to_numeric(df['tree_quantity_clean'], errors='coerce')

# inspect the cleaned column
df[['tree_quantity', 'tree_quantity_clean']].head(20)

   tree_quantity  tree_quantity_clean
0            622                622.0
1            230                230.0
2            240                240.0
3           1457               1457.0
4            250                250.0
5            383                383.0
6            384                384.0
7            383                383.0
8            360                360.0
9            370                370.0
10           370                370.0
11           370                370.0
12           370                370.0
13           370                370.0
14           213                213.0
15          1406               1406.0
16          2986               2986.0
17          1300               1300.0
18           320                320.0
19           533                533.0

In [ ]:
# check the data type of the cleaned column
df['tree_quantity_clean'].dtype

dtype('float64')

In [ ]:
# check rows where the cleaned value is missing
df[df['tree_quantity_clean'].isna()][['tree_quantity', 'tree_quantity_clean']].head(20)

    tree_quantity  tree_quantity_clean
21            NaN                  NaN
22            NaN                  NaN
23            NaN                  NaN
27            NaN                  NaN
30            NaN                  NaN
32            NaN                  NaN
33            NaN                  NaN
71            NaN                  NaN
72            NaN                  NaN
73            NaN                  NaN
74            NaN                  NaN
75            NaN                  NaN
76            NaN                  NaN
77            NaN                  NaN
116           NaN                  NaN

In [ ]:
# inspect latitude values
df['felling_latitude_WGS84'].dropna().unique()[:150]

<ArrowStringArray>
[    '36,57689304',     '36,60223799',   '36,6099778174',     '36,62178904',
     '36,61617144',     '36,75292427',     '36,79982924',     '36,76518276',
     '36,74800409',     '36,83427701',
 ...
   '3.740.907.027', '372.121.213.191',   '3.772.321.973',   '3.772.025.389',
   '3.773.347.515',   '3.770.275.388',   '3.774.985.902',     '37,33831616',
   '3.794.319.167',   '3.794.324.354']
Length: 150, dtype: str

In [ ]:
# inspect longitude values
df['felling_longitude_WGS84'].dropna().unique()[:150]

<ArrowStringArray>
[  '-5,509202381', ' -5,6019132409',  '-5,4648038479',   '-5,518366056',
   '-5,474945207',   '-5,438416824',   '-5,457767886',   '-5,463346881',
   '-5,426723999', ' -5,5176234176',
 ...
 '-5.758.677.855', '-5.721.562.284', '-6.310.845.672', '-6.329.358.355',
 '-6.297.914.018', '-6.471.869.164', '-6.282.946.011', ' -6,1114740609',
 '-6.260.628.257', '-6.151.435.889']
Length: 150, dtype: str

In [ ]:
# clean latitude values
df['latitude_clean'] = (
    df['felling_latitude_WGS84']
    .str.replace(',', '.', regex=False)
    .str.replace(r'(?<=\d)\.(?=.*\.)', '', regex=True)
)

# convert latitude to numeric
df['latitude_clean'] = pd.to_numeric(df['latitude_clean'], errors='coerce')

# inspect original and cleaned latitude values
df[['felling_latitude_WGS84', 'latitude_clean']].dropna().head(30)

   felling_latitude_WGS84  latitude_clean
0             36,57689304    3.657689e+01
1             36,60223799    3.660224e+01
2           36,6099778174    3.660998e+01
3             36,62178904    3.662179e+01
4             36,61617144    3.661617e+01
5             36,75292427    3.675292e+01
6             36,79982924    3.679983e+01
7             36,76518276    3.676518e+01
8             36,74800409    3.674800e+01
9             36,83427701    3.683428e+01
10            36,83170657    3.683171e+01
11            36,84293228    3.684293e+01
12          36,8340336855    3.683403e+01
13          36,8202832219    3.682028e+01
14            36,79936876    3.679937e+01
15            36,50804025    3.650804e+01
16            36,52543016    3.652543e+01
17            36,58488386    3.658488e+01
18            36,61847484    3.661847e+01
19            36,59685737    3.659686e+01
21            36,60071713    3.660072e+01
22            36,63041184    3.663041e+01
23    365.595.086.100.001    3.655951e+11
30            36,52543016    3.652543e+01
32            36,57689304    3.657689e+01
33    365.595.086.100.001    3.655951e+11
34            36,56451668    3.656452e+01
35            36,93788809    3.693789e+01
36            36,69032254    3.669032e+01
37             36,7000286    3.670003e+01

In [ ]:
# clean longitude values
df['longitude_clean'] = (
    df['felling_longitude_WGS84']
    .str.replace(',', '.', regex=False)
    .str.replace(r'(?<=\d)\.(?=.*\.)', '', regex=True)
)

# convert longitude to numeric
df['longitude_clean'] = pd.to_numeric(df['longitude_clean'], errors='coerce')

# inspect original and cleaned longitude values
df[['felling_longitude_WGS84', 'longitude_clean']].dropna().head(30)

   felling_longitude_WGS84  longitude_clean
0             -5,509202381    -5.509202e+00
1            -5,6019132409    -5.601913e+00
2            -5,4648038479    -5.464804e+00
3             -5,518366056    -5.518366e+00
4             -5,474945207    -5.474945e+00
5             -5,438416824    -5.438417e+00
6             -5,457767886    -5.457768e+00
7             -5,463346881    -5.463347e+00
8             -5,426723999    -5.426724e+00
9            -5,5176234176    -5.517623e+00
10           -5,5044698646    -5.504470e+00
11            -5,520069592    -5.520070e+00
12            -5,529137619    -5.529138e+00
13         -5,5273083452\n    -5.527308e+00
14            -5,518731601    -5.518732e+00
15            -5,576951442    -5.576951e+00
16            -5,583841408    -5.583841e+00
17            -5,444877644    -5.444878e+00
18            -5,417707898    -5.417708e+00
19            -5,440138557    -5.440139e+00
21             -5,47458295    -5.474583e+00
22            -5,488708528    -5.488709e+00
23    -558.258.030.799.993    -5.582580e+11
30            -5,583841408    -5.583841e+00
32            -5,509202381    -5.509202e+00
33    -558.258.030.799.993    -5.582580e+11
34              -5,5110559    -5.511056e+00
35            -5,107281846    -5.107282e+00
36            -5,573256974    -5.573257e+00
37           -5,5031861539    -5.503186e+00

In [ ]:
# check summary statistics for cleaned coordinates
df[['latitude_clean', 'longitude_clean']].describe()

       latitude_clean  longitude_clean
count    2.210000e+02     2.210000e+02
mean     3.372879e+09    -5.059300e+09
std      3.469415e+10     5.298573e+10
min      3.630782e+01    -5.582580e+11
25%      3.680058e+01    -6.420850e+06
50%      3.732810e+06    -6.213769e+06
75%      3.767119e+06    -5.571469e+00
max      3.655951e+11    -5.107282e+00

In [ ]:
# count valid cleaned coordinates
df[['latitude_clean', 'longitude_clean']].notna().sum()

latitude_clean     221
longitude_clean    221
dtype: int64

In [ ]:
# inspect rows with suspicious latitude values
df[
    (df['latitude_clean'] < 30) | (df['latitude_clean'] > 40)
][['felling_latitude_WGS84', 'latitude_clean']].head(30)

    felling_latitude_WGS84  latitude_clean
23     365.595.086.100.001    3.655951e+11
33     365.595.086.100.001    3.655951e+11
79         372.623.456.028    3.726235e+08
80           3.732.007.264    3.732007e+06
81           3.729.350.437    3.729350e+06
82           3.734.899.709    3.734900e+06
83         373.331.629.207    3.733316e+08
84           3.735.951.484    3.735951e+06
85           3.737.315.932    3.737316e+06
86           3.731.139.073    3.731139e+06
87           3.734.288.999    3.734289e+06
88           3.731.127.133    3.731127e+06
89         372.609.626.924    3.726096e+08
90           3.735.584.015    3.735584e+06
91           3.725.192.428    3.725192e+06
92           3.725.996.497    3.725996e+06
93           3.735.186.627    3.735187e+06
94           3.727.200.002    3.727200e+06
96           3.734.105.568    3.734106e+06
97           3.732.809.507    3.732810e+06
98           3.734.130.743    3.734131e+06
99           3.733.060.686    3.733061e+06
100          3.727.918.534    3.727919e+06
101          3.731.953.845    3.731954e+06
102          3.748.862.159    3.748862e+06
103          3.728.457.871    3.728458e+06
104          3.726.177.391    3.726177e+06
105          3.724.566.317    3.724566e+06
118          3.732.097.273    3.732097e+06
119          3.735.224.153    3.735224e+06

In [ ]:
# inspect rows with suspicious longitude values
df[
    (df['longitude_clean'] > 0) | (df['longitude_clean'] < -10)
][['felling_longitude_WGS84', 'longitude_clean']].head(30)

    felling_longitude_WGS84  longitude_clean
23     -558.258.030.799.993    -5.582580e+11
33     -558.258.030.799.993    -5.582580e+11
79          -64.647.598.008    -6.464760e+07
80           -6.475.037.122    -6.475037e+06
81           -6.545.288.959    -6.545289e+06
82           -6.570.694.843    -6.570695e+06
83           -6.424.401.461    -6.424401e+06
84             -636.074.504    -6.360745e+05
85           -6.383.912.618    -6.383913e+06
86           -6.420.850.387    -6.420850e+06
87           -6.467.856.282    -6.467856e+06
88           -6.364.159.217    -6.364159e+06
89           -6.634.794.511    -6.634795e+06
90           -6.438.208.807    -6.438209e+06
91           -6.256.546.246    -6.256546e+06
92           -6.230.187.029    -6.230187e+06
93           -6.213.768.561    -6.213769e+06
94           -6.191.586.913    -6.191587e+06
96           -6.308.886.794    -6.308887e+06
97           -6.333.664.706    -6.333665e+06
98           -6.341.364.825    -6.341365e+06
99           -6.287.491.349    -6.287491e+06
100          -6.317.927.291    -6.317927e+06
101            -633.393.354    -6.333934e+05
102         -62.129.359.643    -6.212936e+07
103            -619.580.745    -6.195807e+05
104          -6.279.890.135    -6.279890e+06
105          -6.343.690.193    -6.343690e+06
118          -6.207.600.172    -6.207600e+06
119          -6.239.882.548    -6.239883e+06

In [ ]:
# remove dots used as thousands separators in coordinates
df['latitude_clean'] = (
    df['felling_latitude_WGS84']
    .astype(str)
    .str.replace('.', '', regex=False)
)

df['longitude_clean'] = (
    df['felling_longitude_WGS84']
    .astype(str)
    .str.replace('.', '', regex=False)
)

# convert to numeric
df['latitude_clean'] = pd.to_numeric(df['latitude_clean'], errors='coerce')
df['longitude_clean'] = pd.to_numeric(df['longitude_clean'], errors='coerce')

# divide by 1000000 because the decimal point was lost
df['latitude_clean'] = df['latitude_clean'] / 1000000
df['longitude_clean'] = df['longitude_clean'] / 1000000

In [ ]:
df[['latitude_clean', 'longitude_clean']].describe()

       latitude_clean  longitude_clean
count    1.530000e+02     1.530000e+02
mean     4.871937e+06    -7.307877e+06
std      4.165121e+07     6.361547e+07
min      3.732526e+02    -5.582580e+08
25%      3.732097e+03    -6.545289e+03
50%      3.737316e+03    -6.329358e+03
75%      3.716062e+05    -6.207600e+03
max      3.655951e+08    -5.746374e+02

In [ ]:
# keep only plausible coordinates for southern Spain
df.loc[
    (df['latitude_clean'] < 35) | (df['latitude_clean'] > 39),
    'latitude_clean'
] = pd.NA

df.loc[
    (df['longitude_clean'] < -8) | (df['longitude_clean'] > -4),
    'longitude_clean'
] = pd.NA

In [ ]:
# check summary statistics after filtering implausible coordinates
df[['latitude_clean', 'longitude_clean']].describe()

       latitude_clean  longitude_clean
count             0.0              0.0
mean              NaN              NaN
std               NaN              NaN
min               NaN              NaN
25%               NaN              NaN
50%               NaN              NaN
75%               NaN              NaN
max               NaN              NaN

In [ ]:
# count valid coordinates after cleaning
df[['latitude_clean', 'longitude_clean']].notna().sum()

latitude_clean     0
longitude_clean    0
dtype: int64

In [ ]:
# functions to clean latitude and longitude values
def clean_latitude(value):
    import pandas as pd
    if pd.isna(value):
        return pd.NA
    
    value = str(value).strip().replace('"', '')
    
    if value in ['N/A', 'NA', '']:
        return pd.NA
    
    # normal decimal format with comma
    if ',' in value and value.count('.') <= 1:
        value = value.replace(',', '.')
        return pd.to_numeric(value, errors='coerce')
    
    # malformed format with many dots
    if value.count('.') > 1:
        digits = value.replace('.', '').replace(',', '').replace('-', '').strip()
        if digits == '':
            return pd.NA
        # latitude in southern Spain should start with 36, 37 or 38
        repaired = digits[:2] + '.' + digits[2:]
        return pd.to_numeric(repaired, errors='coerce')
    
    return pd.to_numeric(value, errors='coerce')


def clean_longitude(value):
    import pandas as pd
    if pd.isna(value):
        return pd.NA
    
    value = str(value).strip().replace('"', '')
    
    if value in ['N/A', 'NA', '']:
        return pd.NA
    
    # normal decimal format with comma
    if ',' in value and value.count('.') <= 1:
        value = value.replace(',', '.')
        return pd.to_numeric(value, errors='coerce')
    
    # malformed format with many dots
    if value.count('.') > 1:
        sign = -1 if '-' in value else 1
        digits = value.replace('.', '').replace(',', '').replace('-', '').strip()
        if digits == '':
            return pd.NA
        # longitude in southern Spain should start with 5, 6 or 7
        repaired = digits[:1] + '.' + digits[1:]
        repaired = pd.to_numeric(repaired, errors='coerce')
        return repaired * sign
    
    return pd.to_numeric(value, errors='coerce')

In [ ]:
# rebuild cleaned coordinate columns from the original raw columns
df['latitude_clean'] = df['felling_latitude_WGS84'].apply(clean_latitude)
df['longitude_clean'] = df['felling_longitude_WGS84'].apply(clean_longitude)

In [ ]:
# inspect original and cleaned coordinates
df[
    [
        'felling_latitude_WGS84',
        'latitude_clean',
        'felling_longitude_WGS84',
        'longitude_clean'
    ]
].head(40)

,felling_latitude_WGS84,latitude_clean,felling_longitude_WGS84,longitude_clean
0,"36,57689304",36.576893,"-5,509202381",-5.509202
1,"36,60223799",36.602238,"-5,6019132409",-5.601913
2,"36,6099778174",36.609978,"-5,4648038479",-5.464804
3,"36,62178904",36.621789,"-5,518366056",-5.518366
4,"36,61617144",36.616171,"-5,474945207",-5.474945
5,"36,75292427",36.752924,"-5,438416824",-5.438417
6,"36,79982924",36.799829,"-5,457767886",-5.457768
7,"36,76518276",36.765183,"-5,463346881",-5.463347
8,"36,74800409",36.748004,"-5,426723999",-5.426724
9,"36,83427701",36.834277,"-5,5176234176",-5.517623
10,"36,83170657",36.831707,"-5,5044698646",-5.50447
11,"36,84293228",36.842932,"-5,520069592",-5.52007
12,"36,8340336855",36.834034,"-5,529137619",-5.529138
13,"36,8202832219",36.820283,"-5,5273083452\n",-5.527308
14,"36,79936876",36.799369,"-5,518731601",-5.518732
15,"36,50804025",36.50804,"-5,576951442",-5.576951
16,"36,52543016",36.52543,"-5,583841408",-5.583841
17,"36,58488386",36.584884,"-5,444877644",-5.444878
18,"36,61847484",36.618475,"-5,417707898",-5.417708
19,"36,59685737",36.596857,"-5,440138557",-5.440139
20,NaN,<NA>,NaN,<NA>
21,"36,60071713",36.600717,"-5,47458295",-5.474583
22,"36,63041184",36.630412,"-5,488708528",-5.488709
23,365.595.086.100.001,36.559509,-558.258.030.799.993,-5.58258
24,NaN,<NA>,NaN,<NA>
25,NaN,<NA>,NaN,<NA>
26,NaN,<NA>,NaN,<NA>
27,NaN,<NA>,NaN,<NA>
28,NaN,<NA>,NaN,<NA>
29,NaN,<NA>,NaN,<NA>
30,"36,52543016",36.52543,"-5,583841408",-5.583841
31,NaN,<NA>,NaN,<NA>
32,"36,57689304",36.576893,"-5,509202381",-5.509202
33,365.595.086.100.001,36.559509,-558.258.030.799.993,-5.58258
34,"36,56451668",36.564517,"-5,5110559",-5.511056
35,"36,93788809",36.937888,"-5,107281846",-5.107282
36,"36,69032254",36.690323,"-5,573256974",-5.573257
37,"36,7000286",36.700029,"-5,5031861539",-5.503186
38,"36,7128962400\n",36.712896,"-5,4998977657",-5.499898
39,"36,77882221",36.778822,"-5,447618434",-5.447618

In [ ]:
# check summary statistics for cleaned coordinates
df[['latitude_clean', 'longitude_clean']].describe()

        latitude_clean  longitude_clean
count       221.000000       221.000000
unique      161.000000       161.000000
top          37.341307        -6.341365
freq          5.000000         5.000000

In [ ]:
# convert cleaned coordinates to numeric
df['latitude_clean'] = pd.to_numeric(df['latitude_clean'], errors='coerce')
df['longitude_clean'] = pd.to_numeric(df['longitude_clean'], errors='coerce')

In [ ]:
# check summary statistics again
df[['latitude_clean', 'longitude_clean']].describe()

       latitude_clean  longitude_clean
count      221.000000       221.000000
mean        37.163315        -6.056554
std          0.395019         0.457356
min         36.307821        -7.174165
25%         36.799369        -6.364159
50%         37.311271        -6.212936
75%         37.357908        -5.571195
max         37.952916        -5.107282

In [ ]:
# keep only plausible coordinates for southern Spain
df.loc[
    (df['latitude_clean'] < 35) | (df['latitude_clean'] > 39),
    'latitude_clean'
] = pd.NA

df.loc[
    (df['longitude_clean'] < -8) | (df['longitude_clean'] > -4),
    'longitude_clean'
] = pd.NA

In [ ]:
# count valid coordinates after filtering
df[['latitude_clean', 'longitude_clean']].notna().sum()

latitude_clean     221
longitude_clean    221
dtype: int64

In [ ]:
# inspect possible remaining strange latitude values
df[
    (df['latitude_clean'] < 35) | (df['latitude_clean'] > 39)
][
    ['felling_latitude_WGS84', 'latitude_clean']
]

Empty DataFrame
Columns: [felling_latitude_WGS84, latitude_clean]
Index: []

In [ ]:
# inspect possible remaining strange longitude values
df[
    (df['longitude_clean'] < -8) | (df['longitude_clean'] > -4)
][
    ['felling_longitude_WGS84', 'longitude_clean']
]

Empty DataFrame
Columns: [felling_longitude_WGS84, longitude_clean]
Index: []

In [ ]:
# inspect extreme coordinate values
df.sort_values('latitude_clean')[[
    'latitude_clean',
    'longitude_clean'
]].head(10)

df.sort_values('latitude_clean', ascending=False)[[
    'latitude_clean',
    'longitude_clean'
]].head(10)

     latitude_clean  longitude_clean
396       37.952916        -6.220695
395       37.944405        -6.233912
383       37.943244        -6.151436
378       37.943192        -6.260628
394       37.935284        -6.231529
208       37.790393        -6.491343
214       37.784023        -6.472098
397       37.784023        -6.472098
215       37.763390        -6.386596
252       37.749859        -6.282946

In [ ]:
# inspect province values
df['province'].value_counts(dropna=False)

province
Sevilla    204
Huelva     136
Cádiz       66
Málaga      11
Malaga       2
Name: count, dtype: int64

In [ ]:
# create cleaned province column
df['province_clean'] = (
    df['province']
    .astype(str)
    .str.strip()
    .str.title()
)

In [ ]:
# inspect cleaned province values
df['province_clean'].value_counts(dropna=False)

province_clean
Sevilla    204
Huelva     136
Cádiz       66
Málaga      11
Malaga       2
Name: count, dtype: int64

In [ ]:
# standardize Málaga spelling
df['province_clean'] = df['province_clean'].replace({
    'Malaga': 'Málaga'
})

In [ ]:
# inspect province values again
df['province_clean'].value_counts(dropna=False)

province_clean
Sevilla    204
Huelva     136
Cádiz       66
Málaga      13
Name: count, dtype: int64

In [ ]:
# inspect municipality values
df['municipality'].value_counts(dropna=False)

municipality
Utrera                         69
Almonte                        32
Hinojos                        31
Jeréz de la Frontera           22
Carmona                        18
                               ..
Bollullos de la Mitación,       1
Gelves                          1
Arahal                          1
El Real de la Jara              1
La Puebla del Río               1
Name: count, Length: 72, dtype: int64

In [ ]:
# create cleaned municipality column
df['municipality_clean'] = (
    df['municipality']
    .astype(str)
    .str.strip()
    .str.title()
)

In [ ]:
# inspect cleaned municipality values
df['municipality_clean'].value_counts(dropna=False)

municipality_clean
Utrera                       69
Almonte                      32
Hinojos                      31
Jeréz De La Frontera         22
Carmona                      18
                             ..
Bollullos De La Mitación,     1
Gelves                        1
Arahal                        1
El Real De La Jara            1
La Puebla Del Río             1
Name: count, Length: 70, dtype: int64

In [ ]:
sorted(df['municipality_clean'].unique())

['Alcalá De Guadaíra',
 'Alcalá De Los Gazules',
 'Alcalá De Los Gazules,',
 'Alcalá Del Valle',
 'Algodonales',
 'Almonte',
 'Alosno',
 'Arahal',
 'Arcos De La Frontera',
 'Aznalcázar',
 'Aznalcóllar',
 'Benacazón',
 'Benaocaz',
 'Bollullos De La Mitación',
 'Bollullos De La Mitación,',
 'Bollullos Par Del Condado',
 'Bonares',
 'Cala',
 'Carmona',
 'Carrión De Los Céspedes',
 'Castellar De La Frontera',
 'Chucena',
 'Cortes De La Frontera',
 'Dos Hermanas',
 'El Bosque',
 'El Castillo De Las Guardas',
 'El Cerro De Andévalo',
 'El Garrobo',
 'El Real De La Jara',
 'Espartinas',
 'Gelves',
 'Gibraleón',
 'Grazalema',
 'Higuera De La Sierra',
 'Hinojos',
 'Huelva',
 'Huevar',
 'Huévar',
 'Jeréz De La Frontera',
 'Jimena De La Frontera',
 'La Granada Del Río Tinto',
 'La Puebla Del Río',
 'Los Molares',
 'Lucena Del Puerto',
 'Marchena',
 'Moguer',
 'Niebla',
 'Paradas',
 'Pilas',
 'Prado Del Rey',
 'Rociana Del Condado',
 'Ronda',
 'San Bartolomé De La Torre',
 'San Juan Del Puerto',
 'Sanlúcar La Mayor',
 'Santa Olalla Del Cala',
 'Sevilla',
 'Tocina',
 'Trigueros',
 'Ubrique',
 'Umbrete',
 'Utrera',
 'Valverde Del Camino',
 'Villa Nueva Del Ariscal',
 'Villalba Del Alcor',
 'Villamanrique De La Condesa',
 'Villanueva De Las Cruces',
 'Villarrasa',
 'Zahara De La Sierra',
 'Zufre']

In [ ]:
# create and clean municipality column
df['municipality_clean'] = (
    df['municipality']
    .astype('string')
    .str.strip()
    .str.replace(r',$', '', regex=True)          # remove commas at the end
    .str.replace(r'\s+', ' ', regex=True)        # remove duplicated spaces
    .str.title()                                 # standardize capitalization
    .str.replace(r'\bDe\b', 'de', regex=True)
    .str.replace(r'\bDel\b', 'del', regex=True)
    .str.replace(r'\bLa\b', 'la', regex=True)
    .str.replace(r'\bLas\b', 'las', regex=True)
    .str.replace(r'\bLos\b', 'los', regex=True)
    .str.replace(r'\bY\b', 'y', regex=True)
)

# manual corrections for specific municipality names
df['municipality_clean'] = df['municipality_clean'].replace({
    'Jeréz de la Frontera': 'Jerez de la Frontera',
    'Huevar': 'Huévar',
    'El Cerro de Andevalo': 'El Cerro de Andévalo',
    'Villa Nueva del Ariscal': 'Villanueva del Ariscal'
})

In [ ]:
# inspect cleaned municipality values
sorted(df['municipality_clean'].dropna().unique())

['Alcalá de Guadaíra',
 'Alcalá de los Gazules',
 'Alcalá del Valle',
 'Algodonales',
 'Almonte',
 'Alosno',
 'Arahal',
 'Arcos de la Frontera',
 'Aznalcázar',
 'Aznalcóllar',
 'Benacazón',
 'Benaocaz',
 'Bollullos Par del Condado',
 'Bollullos de la Mitación',
 'Bonares',
 'Cala',
 'Carmona',
 'Carrión de los Céspedes',
 'Castellar de la Frontera',
 'Chucena',
 'Cortes de la Frontera',
 'Dos Hermanas',
 'El Bosque',
 'El Castillo de las Guardas',
 'El Cerro de Andévalo',
 'El Garrobo',
 'El Real de la Jara',
 'Espartinas',
 'Gelves',
 'Gibraleón',
 'Grazalema',
 'Higuera de la Sierra',
 'Hinojos',
 'Huelva',
 'Huévar',
 'Jerez de la Frontera',
 'Jimena de la Frontera',
 'Lucena del Puerto',
 'Marchena',
 'Moguer',
 'Niebla',
 'Paradas',
 'Pilas',
 'Prado del Rey',
 'Rociana del Condado',
 'Ronda',
 'San Bartolomé de la Torre',
 'San Juan del Puerto',
 'Sanlúcar la Mayor',
 'Santa Olalla del Cala',
 'Sevilla',
 'Tocina',
 'Trigueros',
 'Ubrique',
 'Umbrete',
 'Utrera',
 'Valverde del Camino',
 'Villalba del Alcor',
 'Villamanrique de la Condesa',
 'Villanueva de las Cruces',
 'Villanueva del Ariscal',
 'Villarrasa',
 'Zahara de la Sierra',
 'Zufre',
 'la Granada del Río Tinto',
 'la Puebla del Río',
 'los Molares']

In [ ]:
df['municipality_clean'] = df['municipality_clean'].replace({
    'la Granada del Río Tinto': 'La Granada del Río Tinto',
    'la Puebla del Río': 'La Puebla del Río',
    'los Molares': 'Los Molares'
})

In [ ]:
# inspect cleaned municipality values again
sorted(df['municipality_clean'].dropna().unique())

['Alcalá de Guadaíra',
 'Alcalá de los Gazules',
 'Alcalá del Valle',
 'Algodonales',
 'Almonte',
 'Alosno',
 'Arahal',
 'Arcos de la Frontera',
 'Aznalcázar',
 'Aznalcóllar',
 'Benacazón',
 'Benaocaz',
 'Bollullos Par del Condado',
 'Bollullos de la Mitación',
 'Bonares',
 'Cala',
 'Carmona',
 'Carrión de los Céspedes',
 'Castellar de la Frontera',
 'Chucena',
 'Cortes de la Frontera',
 'Dos Hermanas',
 'El Bosque',
 'El Castillo de las Guardas',
 'El Cerro de Andévalo',
 'El Garrobo',
 'El Real de la Jara',
 'Espartinas',
 'Gelves',
 'Gibraleón',
 'Grazalema',
 'Higuera de la Sierra',
 'Hinojos',
 'Huelva',
 'Huévar',
 'Jerez de la Frontera',
 'Jimena de la Frontera',
 'La Granada del Río Tinto',
 'La Puebla del Río',
 'Los Molares',
 'Lucena del Puerto',
 'Marchena',
 'Moguer',
 'Niebla',
 'Paradas',
 'Pilas',
 'Prado del Rey',
 'Rociana del Condado',
 'Ronda',
 'San Bartolomé de la Torre',
 'San Juan del Puerto',
 'Sanlúcar la Mayor',
 'Santa Olalla del Cala',
 'Sevilla',
 'Tocina',
 'Trigueros',
 'Ubrique',
 'Umbrete',
 'Utrera',
 'Valverde del Camino',
 'Villalba del Alcor',
 'Villamanrique de la Condesa',
 'Villanueva de las Cruces',
 'Villanueva del Ariscal',
 'Villarrasa',
 'Zahara de la Sierra',
 'Zufre']

In [ ]:
# inspect municipality values with counts
df['municipality_clean'].value_counts(dropna=False)

municipality_clean
Utrera                  69
Almonte                 32
Hinojos                 31
Jerez de la Frontera    22
Carmona                 18
                        ..
Moguer                   1
Gelves                   1
Arahal                   1
El Real de la Jara       1
La Puebla del Río        1
Name: count, Length: 67, dtype: int64[pyarrow]

In [ ]:
df.columns

Index(['felling_period', 'felling_toponymy_source', 'felling_toponymy_MTN25',
       'felling_latitude_WGS84', 'felling_longitude_WGS84', 'municipality',
       'province', 'landowner_type', 'landowner_name', 'tree_species',
       'tree_quantity', 'tree_quantity_clean', 'latitude_clean',
       'longitude_clean', 'province_clean', 'municipality_clean'],
      dtype='str')

In [ ]:
# inspect landowner type values
df['landowner_type'].value_counts(dropna=False)

landowner_type
private                       164
comunal                        88
noble estate                   87
ecclesiastic                   30
NaN                            20
 ecclesiastic                   7
assistance institution          6
private, ecclesiastic           4
 noble estate                   4
fallow land                     3
noble estate, ecclesiastic      2
private, comunal                1
private, noble estate           1
comunal, ecclesiastic           1
assistance institution          1
Name: count, dtype: int64

In [ ]:
# create cleaned landowner type column
df['landowner_type_clean'] = (
    df['landowner_type']
    .astype('string')
    .str.strip()
    .str.lower()
    .str.replace(r'\s*,\s*', ', ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
)

In [ ]:
# inspect cleaned landowner type values
df['landowner_type_clean'].value_counts(dropna=False)

landowner_type_clean
private                       164
noble estate                   91
comunal                        88
ecclesiastic                   37
<NA>                           20
assistance institution          7
private, ecclesiastic           4
fallow land                     3
noble estate, ecclesiastic      2
private, comunal                1
private, noble estate           1
comunal, ecclesiastic           1
Name: count, dtype: int64[pyarrow]

In [ ]:
# inspect unique cleaned landowner types
sorted(df['landowner_type_clean'].dropna().unique())

['assistance institution',
 'comunal',
 'comunal, ecclesiastic',
 'ecclesiastic',
 'fallow land',
 'noble estate',
 'noble estate, ecclesiastic',
 'private',
 'private, comunal',
 'private, ecclesiastic',
 'private, noble estate']

In [ ]:
# inspect landowner name values
df['landowner_name'].value_counts(dropna=False)

landowner_name
NaN                                                                        25
Jerez de la Frontera                                                       16
Jimena de la Frontera                                                      14
Duque de Arcos                                                             13
Marqués de Astorga                                                          7
                                                                           ..
Misericórdia                                                                1
Benacazón                                                                   1
Marqués de Sauzo, Marquesa de Villa Nueva del Prado                         1
Bartolomé Rodriguez, Joaquín de Tróia, José Mabaes Ayala, Ursula Morgas     1
Vigario de El Castillo de las Guardas                                       1
Name: count, Length: 264, dtype: int64

In [ ]:
# create cleaned landowner name column
df['landowner_name_clean'] = (
    df['landowner_name']
    .astype('string')
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

In [ ]:
# inspect cleaned landowner names
df['landowner_name_clean'].value_counts(dropna=False).head(50)

landowner_name_clean
<NA>                                                                                             25
Jerez de la Frontera                                                                             16
Jimena de la Frontera                                                                            14
Duque de Arcos                                                                                   13
Marqués de Astorga                                                                                7
Marqués de Saltillo                                                                               7
Cortes de la frontera                                                                             6
Duque de Medina Sidónia                                                                           6
Rociana del Condado                                                                               6
Orden de Malta                                                                                    6
Conde de Torrejón                                                                                 5
Marqués de Dos Hermanas                                                                           5
Vigário de Castilo de las Guardas                                                                 5
Ignacio de Castañeda                                                                              4
El Castillo de las Guardas                                                                        4
Marqués de Las Torres                                                                             3
Catedral de Sevilla                                                                               3
Marqués de La Fuente                                                                              3
Cardenal Infante Luis Antonio Jaime de Borbón y Farnesio                                          3
Marqués de Gelo                                                                                   3
Misericordia de Sevilla                                                                           3
Aznalcóllar                                                                                       3
Marquesa de Astorga                                                                               3
Pedro Manuel Motezuma                                                                             2
ronda                                                                                             2
Castellar de la Frontera                                                                          2
Almonte                                                                                           2
Duque de Medida Sidonia                                                                           2
Marqués de Torralba                                                                               2
Marqués de Villafranca                                                                            2
Duque de Alba                                                                                     2
Marqués de Torres                                                                                 2
José Domínguez, Hermandad de Nuestra Señora del Rosario,Convento de Nuestra Señora del Pópulo     2
Manuel Ortiz                                                                                      2
Conde-Duque de Olivares                                                                           2
Marquesa de La Motilla, Convento de San Pablo de Sevilla                                          2
Alosno                                                                                            2
San Bartolomé de la Torre                                                                         2
Niebla                                                                                            2
Trigueros                                                                                         2
Duque de Medinacelli                                                                              2
San Juan del Puerto                                                                               2
Zufre                                                                                             2
Marqués de la Fuente                                                                              2
El Garrobo                                                                                        2
Francisco Rodríguez                                                                               2
Pedro Ponce                                                                                       2
Diego Martínez de la Paba,                                                                        2
Antonio de Flores,                                                                                2
Jose Martinez Carmona                                                                             2
Name: count, dtype: int64[pyarrow]

In [ ]:
# inspect unique landowner names alphabetically
sorted(df['landowner_name_clean'].dropna().unique())[:100]

['Abadia del Monasterio de San Benito de Sevilla',
 'Alcalá de los Gazules',
 'Alcalá del Valle',
 'Almonte',
 'Alonso Acevedo',
 'Alonso Gregório Domingues de Rivas',
 'Alonso Martin',
 'Alonso Perez Mota, Francisco Joseph Vayas, Fernando Vayas Mota',
 'Alonso Segura',
 'Alosno',
 'Ana Barrientos',
 'Ana Franco',
 'Andres Bueno,',
 'Andres Sánchez',
 'Antonio Montedoca',
 'Antonio Perez, Maria Dominguez',
 'Antonio Quintanilla',
 'Antonio de Flores,',
 'António Marquez',
 'António Ojedo',
 'Aznalcázar',
 'Aznalcóllar',
 'Bartolomé Delgado',
 'Bartolomé Rodriguez, Joaquín de Tróia, José Mabaes Ayala, Ursula Morgas',
 'Bartolomé Romero',
 'Bartolomé Velez Jurado',
 'Bartolomé de Albarán',
 'Bartolomé de Palma',
 'Benacazón',
 'Blas Fernández',
 'Bollullos del Condado',
 'Bonares',
 'Cala',
 'Canon Lazaro',
 'Cardenal Infante Luis Antonio Jaime de Borbón y Farnesio',
 'Casa de la Misericordia de Sevilla',
 'Castellar de la Frontera',
 'Catedral de Sevilla',
 'Cathedral of Sevilla',
 'Chucena',
 'Clérigos Cereros',
 'Compañía de Jesus',
 'Conde de Benajiar',
 'Conde de Gerena',
 'Conde de Mejorada',
 'Conde de Torrejón',
 'Conde de Torrubia',
 'Conde-Duque de Olivares',
 'Condesa de Arenales',
 'Convent de La Concepción',
 'Convento de San Agustin de Sevilla',
 'Convento de San Juan Baptista de la Morañina, Hermandad de Nuestra Señora de Gracia',
 'Cortes de la frontera',
 'Cristobal Bermudez',
 'Cristobal Franco',
 'Cristoval de Aranda, Juan de Medina, Domingos Valeras, Joseph de Solis',
 'Cura de Santiago de Carmona',
 'Diego Bermudez',
 'Diego José de Vargas',
 'Diego Martínez de la Paba,',
 'Diego Ramos',
 'Diego Urbaneja',
 'Diego de Alcalá',
 'Diego de Guzman',
 'Diego de Soto',
 'Duque de Alba',
 'Duque de Alcalá',
 'Duque de Arcos',
 'Duque de Béjar',
 'Duque de Medida Sidonia',
 'Duque de Medina Sidónia',
 'Duque de Medinacelli',
 'Duque de Santo Estevan',
 'Duquesa de Alba',
 'Duquesa de Veraguas',
 'El Castillo de las Guardas',
 'El Cerro de Andévalo',
 'El Garrobo',
 'El Real de la Jara',
 'Elvira Varela',
 'Estebán Garcia',
 'Fabrica de Ia Iglesia de Almonte',
 'Felipe Cordon',
 'Felix Cataño,',
 'Fernando Barrientos',
 'Fernando y Martin Barba',
 'Filipe de Acosta, Maria Monsaibe, Pedro Briones',
 'Frabrica de la Iglesia Parroquial de San Pablo de Aznalcazar',
 'Frabrica de la Iglesia de Santa Maria de Utrera',
 'Francisco Almoriña',
 'Francisco Antonio Maestre',
 'Francisco Beltran',
 'Francisco Bolaños',
 'Francisco Calero',
 'Francisco Cepeda',
 'Francisco Esquível',
 'Francisco Jiménez',
 'Francisco Melendez',
 'Francisco Moralez',
 'Francisco Osorno']

In [ ]:
# inspect landowner name values
df['landowner_name'].value_counts(dropna=False).head(50)

landowner_name
NaN                                                                                               25
Jerez de la Frontera                                                                              16
Jimena de la Frontera                                                                             14
Duque de Arcos                                                                                    13
Marqués de Astorga                                                                                 7
Marqués de Saltillo                                                                                7
Cortes de la frontera                                                                              6
Duque de Medina Sidónia                                                                            6
Rociana del Condado                                                                                5
Vigário de Castilo de las Guardas                                                                  5
Ignacio de Castañeda                                                                               4
Orden de Malta                                                                                     4
Marqués de Dos Hermanas                                                                            4
El Castillo de las Guardas                                                                         4
Catedral de Sevilla                                                                                3
Marqués de La Fuente                                                                               3
Conde de Torrejón                                                                                  3
Marqués de Gelo                                                                                    3
Aznalcóllar                                                                                        3
Marquesa de Astorga                                                                                3
Pedro Manuel Motezuma                                                                              2
ronda                                                                                              2
Almonte                                                                                            2
Duque de Medida Sidonia                                                                            2
Marqués de Torralba                                                                                2
Conde de  Torrejón                                                                                 2
Marqués de Villafranca                                                                             2
Duque de Alba                                                                                      2
Marqués de Torres                                                                                  2
José Domínguez, Hermandad de Nuestra Señora del Rosario,Convento de Nuestra Señora del Pópulo      2
Misericordia  de Sevilla                                                                           2
Manuel Ortiz                                                                                       2
Conde-Duque de Olivares                                                                            2
Marqués de  Las Torres                                                                             2
Cardenal Infante Luis Antonio Jaime de Borbón y Farnesio                                           2
Alosno                                                                                             2
Niebla                                                                                             2
Trigueros                                                                                          2
Duque de Medinacelli                                                                               2
San Juan del Puerto                                                                                2
Marqués de la Fuente                                                                               2
El Garrobo                                                                                         2
Francisco Rodríguez                                                                                2
Pedro Ponce                                                                                        2
Diego Martínez de la Paba,                                                                         2
 Antonio de Flores,                                                                                2
Jose Martinez Carmona                                                                              2
Pedro Alaran                                                                                       2
Bartolomé de Palma                                                                                 2
Ana Franco                                                                                         2
Name: count, dtype: int64

In [ ]:
# inspect all unique landowner names alphabetically
sorted(df['landowner_name_clean'].dropna().unique())

['Abadia del Monasterio de San Benito de Sevilla',
 'Alcalá de los Gazules',
 'Alcalá del Valle',
 'Almonte',
 'Alonso Acevedo',
 'Alonso Gregório Domingues de Rivas',
 'Alonso Martin',
 'Alonso Perez Mota, Francisco Joseph Vayas, Fernando Vayas Mota',
 'Alonso Segura',
 'Alosno',
 'Ana Barrientos',
 'Ana Franco',
 'Andres Bueno,',
 'Andres Sánchez',
 'Antonio Montedoca',
 'Antonio Perez, Maria Dominguez',
 'Antonio Quintanilla',
 'Antonio de Flores,',
 'António Marquez',
 'António Ojedo',
 'Aznalcázar',
 'Aznalcóllar',
 'Bartolomé Delgado',
 'Bartolomé Rodriguez, Joaquín de Tróia, José Mabaes Ayala, Ursula Morgas',
 'Bartolomé Romero',
 'Bartolomé Velez Jurado',
 'Bartolomé de Albarán',
 'Bartolomé de Palma',
 'Benacazón',
 'Blas Fernández',
 'Bollullos del Condado',
 'Bonares',
 'Cala',
 'Canon Lazaro',
 'Cardenal Infante Luis Antonio Jaime de Borbón y Farnesio',
 'Casa de la Misericordia de Sevilla',
 'Castellar de la Frontera',
 'Catedral de Sevilla',
 'Cathedral of Sevilla',
 'Chucena',
 'Clérigos Cereros',
 'Compañía de Jesus',
 'Conde de Benajiar',
 'Conde de Gerena',
 'Conde de Mejorada',
 'Conde de Torrejón',
 'Conde de Torrubia',
 'Conde-Duque de Olivares',
 'Condesa de Arenales',
 'Convent de La Concepción',
 'Convento de San Agustin de Sevilla',
 'Convento de San Juan Baptista de la Morañina, Hermandad de Nuestra Señora de Gracia',
 'Cortes de la frontera',
 'Cristobal Bermudez',
 'Cristobal Franco',
 'Cristoval de Aranda, Juan de Medina, Domingos Valeras, Joseph de Solis',
 'Cura de Santiago de Carmona',
 'Diego Bermudez',
 'Diego José de Vargas',
 'Diego Martínez de la Paba,',
 'Diego Ramos',
 'Diego Urbaneja',
 'Diego de Alcalá',
 'Diego de Guzman',
 'Diego de Soto',
 'Duque de Alba',
 'Duque de Alcalá',
 'Duque de Arcos',
 'Duque de Béjar',
 'Duque de Medida Sidonia',
 'Duque de Medina Sidónia',
 'Duque de Medinacelli',
 'Duque de Santo Estevan',
 'Duquesa de Alba',
 'Duquesa de Veraguas',
 'El Castillo de las Guardas',
 'El Cerro de Andévalo',
 'El Garrobo',
 'El Real de la Jara',
 'Elvira Varela',
 'Estebán Garcia',
 'Fabrica de Ia Iglesia de Almonte',
 'Felipe Cordon',
 'Felix Cataño,',
 'Fernando Barrientos',
 'Fernando y Martin Barba',
 'Filipe de Acosta, Maria Monsaibe, Pedro Briones',
 'Frabrica de la Iglesia Parroquial de San Pablo de Aznalcazar',
 'Frabrica de la Iglesia de Santa Maria de Utrera',
 'Francisco Almoriña',
 'Francisco Antonio Maestre',
 'Francisco Beltran',
 'Francisco Bolaños',
 'Francisco Calero',
 'Francisco Cepeda',
 'Francisco Esquível',
 'Francisco Jiménez',
 'Francisco Melendez',
 'Francisco Moralez',
 'Francisco Osorno',
 'Francisco Parea',
 'Francisco Pedrezo',
 'Francisco Rodriguez',
 'Francisco Rodríguez',
 'Francisco de Torres',
 'Francisco de Vega',
 'Gaspar de Castro',
 'Gerónimo Florencio',
 'Gerónimo Franco',
 'Gerónimo Jiménez',
 'Heirs of Ignácio de Castañeda',
 'Hermandad de Benditas Anias de Hinojos',
 'Hermandad de la Santíssima Trinidad,',
 'Hermandad del Santíssimo Sacramento',
 'Hermita de Nuestra Señora del Rocio',
 'Higuera de la Sierra',
 'Hinojos',
 'Hospice de San Ignacio Hospice de Sevilla',
 'Iglesia Patriarcal de Sevilla',
 'Ignacio de Castañeda',
 'Isabel Suárez',
 'Isabel Tello de Eslava',
 'Jerez de la Frontera',
 'Jerónimo Ramos',
 'Jimena de la Frontera',
 'Jose Alaraz',
 'Jose Martinez Carmona',
 'Jose Naranjo',
 'Josefa María Venegas',
 'Joseph Azevedo, peresbítero',
 'Joseph Dominguez',
 'José Campo, Pedro de los Reyes',
 'José Carlos Tello',
 'José Delgado',
 'José Domínguez, Hermandad de Nuestra Señora del Rosario,Convento de Nuestra Señora del Pópulo',
 'José Florencio',
 'José Sanchez',
 'José Tello de Eslava',
 'José Valdivieso',
 'José Vaquero',
 'José Vargas',
 'José de Castillo, Juan de Almoriña',
 'José de Monsalve',
 'José de Vayas',
 'Juan Almoruña',
 'Juan Antonio Maestre,',
 'Juan Carmona',
 'Juan Faustino Moreno y Figueroa',
 'Juan Gallardo, Julio Cavaleri, Convento de Santa Clara',
 'Juan José Clarebot',
 'Juan Jurado',
 'Juan Ruiz',
 'Juan de Aguilar',
 'Juan de Almoriña',
 'Juan de Asa',
 'Juan de Lamilla',
 'Juan de Sevilla',
 'Juan de Vayas y Motta',
 'Juana de Sarria,',
 'Justo de Cerna',
 'Laura María de Queiros',
 'Lorenzo de Lana',
 'Lucena del Puerto',
 'Lucena del Puerto, Convento de la Luz de Lucena del Puerto',
 'Luis Antonio Cabrera',
 'Luís Hermoso',
 'Maiorazgo de Cabrera',
 'Maiorazgo de Recuero',
 'Manuel Acevedo',
 'Manuel Caton',
 'Manuel Eusebio Varela',
 'Manuel Fernández',
 'Manuel Gil',
 'Manuel Morillo',
 'Manuel Ortiz',
 'Manuel de Medina',
 'Manuel de Saavedra',
 'Manuel de los Reyes',
 'Maques de Valhermoso',
 'Maria Beltrán',
 'Maria Lamilla',
 'Maria de Mendonza , Francisco Samariego',
 'Marquesa de Astorga',
 'Marquesa de La Motilla',
 'Marquesa de La Motilla, Convento de San Pablo de Sevilla',
 'Marqués de Astorga',
 'Marqués de Benamejí',
 'Marqués de Dos Hermanas',
 'Marqués de Gelo',
 'Marqués de La Fuente',
 'Marqués de Las Torres',
 'Marqués de Priego',
 'Marqués de Saltillo',
 'Marqués de Sauzo, Marquesa de Villa Nueva del Prado',
 'Marqués de Tablantes',
 'Marqués de Torralba',
 'Marqués de Torres',
 'Marqués de Villa Franca',
 'Marqués de Villafranca',
 'Marqués de la Florida',
 'Marqués de la Fuente',
 'Marqués de la Villa',
 'Mateo del Castillo',
 'Miguel Roldán',
 'Miguel de Bustillo',
 'Miguel de Ribas',
 'Misericordia',
 'Misericordia de Sevilla',
 'Misericórdia',
 'Monasterio de la Cartuja de Jerez',
 'Niebla',
 'Nuño Carlos de Villacicencio',
 'Orden de Malta',
 'Order of Malta',
 'Patronato de Pelaez',
 'Patronato de Salas',
 'Pedro Alaran',
 'Pedro Briones',
 'Pedro Diego Estevan',
 'Pedro Manuel Motezuma',
 'Pedro Mendez',
 'Pedro Morales, Marqués de Caozo',
 'Pedro Ordiales',
 'Pedro Parreño',
 'Pedro Ponce',
 'Pedro Roman and other unidentified individual',
 'Pilas',
 'Rafaela Millan',
 'Rociana del Condado',
 'Rodrigo Patronato',
 'Roque de Arena',
 'San Bartolomé de la Torre',
 'San Juan del Puerto',
 'Santa Olalla del Cala',
 'Sebastian Montilla',
 'Simon Naranjo,',
 'Tereza de Campomanes,',
 'Trigueros',
 'Umbrete',
 'Utrera',
 'Valverde del Camino',
 'Vicente Garcia',
 'Vigario de El Castillo de las Guardas',
 'Vigário de Castilo de las Guardas',
 'Villa de Aznalcazar',
 'Villanueva de las Cruces',
 'Widow of Miguel Lamilla, Compañía de Jesus',
 'Zufre',
 'cabildo de la villa de Cala',
 'fabrica de la Iglesia de Cala',
 'ronda',
 'ubrique']

In [ ]:
# apply manual corrections to landowner names
df['landowner_name_clean'] = df['landowner_name_clean'].replace({

    'Alonso Martin': 'Alonso Martín',
    'Alonso Perez Mota, Francisco Joseph Vayas, Fernando Vayas Mota': 'Alonso Pérez Mota, Francisco José Vayas, Fernando Vayas Mota',
    'Andres Bueno': 'Andrés Bueno',
    'Andres Bueno,': 'Andrés Bueno',
    'Andres Sánchez': 'Andrés Sánchez',
    'Antonio Perez, Maria Dominguez': 'Antonio Perez, María Domínguez',
    'António Marquez': 'Antonio Márquez',
    'António Ojedo': 'Antonio Ojedo',

    'Bartolomé Rodriguez, Joaquín de Tróia, José Mabaes Ayala, Ursula Morgas':
        'Bartolomé Rodríguez, Joaquín de Tróia, José Mabaes Ayala, Úrsula Morgas',

    'Cathedral of Sevilla': 'Catedral de Sevilla',
    'Clérigos Cereros': 'Clerigos Cereros',
    'Compañía de Jesus': 'Compañía de Jesús',
    'Convent de La Concepción': 'Convento de La Concepción',
    'Convento de San Agustin de Sevilla': 'Convento de San Agustín de Sevilla',
    'Convento de San Juan Baptista de la Morañina, Hermandad de Nuestra Señora de Gracia':
        'Convento de San Juan Bautista de la Morañina, Hermandad de Nuestra Señora de Gracia',
    'Cortes de la frontera': 'Cortes de la Frontera',

    'Cristobal Bermudez': 'Cristóbal Bermúdez',
    'Cristobal Franco': 'Cristóbal Franco',
    'Cristoval de Aranda, Juan de Medina, Domingos Valeras, Joseph de Solis':
        'Cristóbal de Aranda, Juan de Medina, Domingos Valeras, José de Solís',

    'Diego Bermudez': 'Diego Bermúdez',
    'Diego de Guzman': 'Diego de Guzmán',

    'Duque de Medida Sidonia': 'Duque de Medina Sidonia',
    'Duque de Medina Sidónia': 'Duque de Medina Sidonia',
    'Duque de Santo Estevan': 'Duque de Santo Esteban',

    'Estebán Garcia': 'Estebán García',
    'Felipe Cordon': 'Felipe Cordón',
    'Fernando y Martin Barba': 'Fernando Barba, Martín Barba',

    'Frabrica de la Iglesia Parroquial de San Pablo de Aznalcazar':
        'Fabrica de la Iglesia Parroquial de San Pablo de Aznalcázar',
    'Frabrica de la Iglesia de Santa Maria de Utrera':
        'Fabrica de la Iglesia de Santa Maria de Utrera',

    'Francisco Beltran': 'Francisco Beltrán',
    'Francisco Melendez': 'Francisco Meléndez',
    'Francisco Moralez': 'Francisco Morález',
    'Francisco Rodriguez': 'Francisco Rodríguez',

    'Heirs of Ignácio de Castañeda': 'Ignacio de Castañeda',
    'Hermita de Nuestra Señora del Rocio': 'Hermita de Nuestra Señora del Rocío',
    'Hospice de San Ignacio Hospice de Sevilla': 'Hospicio de San Ignacio de Sevilla',

    'Jerónimo Ramos': 'Gerónimo Ramos',
    'Jose Alaraz': 'José Alaraz',
    'Jose Martinez Carmona': 'José Martinez Carmona',
    'Joseph Azevedo, peresbítero': 'José Azevedo, peresbítero',
    'Joseph Dominguez': 'José Domínguez',
    'José Sanchez': 'José Sánchez',

    'José Domínguez, Hermandad de Nuestra Señora del Rosario,Convento de Nuestra Señora del Pópulo':
        'José Domínguez, Hermandad de Nuestra Señora del Rosario, Convento de Nuestra Señora del Pópulo',

    'Juan de Vayas y Motta': 'Juan de Vayas y Mota',
    'Juana de Sarria': 'Juana de Sarria',
    'Juana de Sarria,': 'Juana de Sarria',

    'Laura María de Queiros': 'Laura María de Quirós',
    'Luís Hermoso': 'Luis Hermoso',

    'Maques de Valhermoso': 'Marqués de Valhermoso',
    'Maria Beltrán': 'María Beltrán',
    'Maria Lamilla': 'María Lamilla',
    'Maria de Mendonza , Francisco Samariego': 'María de Mendonza, Francisco Samariego',

    'Marquesa de Astorga': 'Marquesa de Astorga',
    'Marquesa de La Motilla': 'Marquesa de La Motilla',
    'Marquesa de La Motilla, Convento de San Pablo de Sevilla':
        'Marquesa de La Motilla, Convento de San Pablo de Sevilla',

    'Marqués de Villa Franca': 'Marqués de Villa Franca',
    'Marqués de Villafranca': 'Marqués de Villa Franca',

    'Misericórdia': 'Misericordia',
    'Order of Malta': 'Orden de Malta',

    'Pedro Alaran': 'Pedro Alarán',
    'Pedro Diego Estevan': 'Pedro Diego Esteban',
    'Pedro Roman and other unidentified individual': 'Pedro Román and other unidentified individual',

    'Rafaela Millan': 'Rafaela Millán',
    'Sebastian Montilla': 'Sebastián Montilla',
    'Simon Naranjo': 'Simón Naranjo',
    'Simon Naranjo,': 'Simón Naranjo',

    'Vicente Garcia': 'Vicente García',
    'Vigario de Castilo de las Guardas': 'Vigario de El Castillo de las Guardas',
    'Villa de Aznalcazar': 'Villa de Aznalcázar',

    'fabrica de la Iglesia de Cala': 'Fabrica de la Iglesia de Cala',
    'ronda': 'Ronda',
    'ubrique': 'Ubrique'
})

In [ ]:
# inspect all unique cleaned landowner names alphabetically
sorted(df['landowner_name_clean'].dropna().unique())

['Abadia del Monasterio de San Benito de Sevilla',
 'Alcalá de los Gazules',
 'Alcalá del Valle',
 'Almonte',
 'Alonso Acevedo',
 'Alonso Gregório Domingues de Rivas',
 'Alonso Martín',
 'Alonso Pérez Mota, Francisco José Vayas, Fernando Vayas Mota',
 'Alonso Segura',
 'Alosno',
 'Ana Barrientos',
 'Ana Franco',
 'Andrés Bueno',
 'Andrés Sánchez',
 'Antonio Montedoca',
 'Antonio Márquez',
 'Antonio Ojedo',
 'Antonio Perez, María Domínguez',
 'Antonio Quintanilla',
 'Antonio de Flores,',
 'Aznalcázar',
 'Aznalcóllar',
 'Bartolomé Delgado',
 'Bartolomé Rodríguez, Joaquín de Tróia, José Mabaes Ayala, Úrsula Morgas',
 'Bartolomé Romero',
 'Bartolomé Velez Jurado',
 'Bartolomé de Albarán',
 'Bartolomé de Palma',
 'Benacazón',
 'Blas Fernández',
 'Bollullos del Condado',
 'Bonares',
 'Cala',
 'Canon Lazaro',
 'Cardenal Infante Luis Antonio Jaime de Borbón y Farnesio',
 'Casa de la Misericordia de Sevilla',
 'Castellar de la Frontera',
 'Catedral de Sevilla',
 'Chucena',
 'Clerigos Cereros',
 'Compañía de Jesús',
 'Conde de Benajiar',
 'Conde de Gerena',
 'Conde de Mejorada',
 'Conde de Torrejón',
 'Conde de Torrubia',
 'Conde-Duque de Olivares',
 'Condesa de Arenales',
 'Convento de La Concepción',
 'Convento de San Agustín de Sevilla',
 'Convento de San Juan Bautista de la Morañina, Hermandad de Nuestra Señora de Gracia',
 'Cortes de la Frontera',
 'Cristóbal Bermúdez',
 'Cristóbal Franco',
 'Cristóbal de Aranda, Juan de Medina, Domingos Valeras, José de Solís',
 'Cura de Santiago de Carmona',
 'Diego Bermúdez',
 'Diego José de Vargas',
 'Diego Martínez de la Paba,',
 'Diego Ramos',
 'Diego Urbaneja',
 'Diego de Alcalá',
 'Diego de Guzmán',
 'Diego de Soto',
 'Duque de Alba',
 'Duque de Alcalá',
 'Duque de Arcos',
 'Duque de Béjar',
 'Duque de Medina Sidonia',
 'Duque de Medinacelli',
 'Duque de Santo Esteban',
 'Duquesa de Alba',
 'Duquesa de Veraguas',
 'El Castillo de las Guardas',
 'El Cerro de Andévalo',
 'El Garrobo',
 'El Real de la Jara',
 'Elvira Varela',
 'Estebán García',
 'Fabrica de Ia Iglesia de Almonte',
 'Fabrica de la Iglesia Parroquial de San Pablo de Aznalcázar',
 'Fabrica de la Iglesia de Cala',
 'Fabrica de la Iglesia de Santa Maria de Utrera',
 'Felipe Cordón',
 'Felix Cataño,',
 'Fernando Barba, Martín Barba',
 'Fernando Barrientos',
 'Filipe de Acosta, Maria Monsaibe, Pedro Briones',
 'Francisco Almoriña',
 'Francisco Antonio Maestre',
 'Francisco Beltrán',
 'Francisco Bolaños',
 'Francisco Calero',
 'Francisco Cepeda',
 'Francisco Esquível',
 'Francisco Jiménez',
 'Francisco Meléndez',
 'Francisco Morález',
 'Francisco Osorno',
 'Francisco Parea',
 'Francisco Pedrezo',
 'Francisco Rodríguez',
 'Francisco de Torres',
 'Francisco de Vega',
 'Gaspar de Castro',
 'Gerónimo Florencio',
 'Gerónimo Franco',
 'Gerónimo Jiménez',
 'Gerónimo Ramos',
 'Hermandad de Benditas Anias de Hinojos',
 'Hermandad de la Santíssima Trinidad,',
 'Hermandad del Santíssimo Sacramento',
 'Hermita de Nuestra Señora del Rocío',
 'Higuera de la Sierra',
 'Hinojos',
 'Hospicio de San Ignacio de Sevilla',
 'Iglesia Patriarcal de Sevilla',
 'Ignacio de Castañeda',
 'Isabel Suárez',
 'Isabel Tello de Eslava',
 'Jerez de la Frontera',
 'Jimena de la Frontera',
 'Jose Naranjo',
 'Josefa María Venegas',
 'José Alaraz',
 'José Azevedo, peresbítero',
 'José Campo, Pedro de los Reyes',
 'José Carlos Tello',
 'José Delgado',
 'José Domínguez',
 'José Domínguez, Hermandad de Nuestra Señora del Rosario, Convento de Nuestra Señora del Pópulo',
 'José Florencio',
 'José Martinez Carmona',
 'José Sánchez',
 'José Tello de Eslava',
 'José Valdivieso',
 'José Vaquero',
 'José Vargas',
 'José de Castillo, Juan de Almoriña',
 'José de Monsalve',
 'José de Vayas',
 'Juan Almoruña',
 'Juan Antonio Maestre,',
 'Juan Carmona',
 'Juan Faustino Moreno y Figueroa',
 'Juan Gallardo, Julio Cavaleri, Convento de Santa Clara',
 'Juan José Clarebot',
 'Juan Jurado',
 'Juan Ruiz',
 'Juan de Aguilar',
 'Juan de Almoriña',
 'Juan de Asa',
 'Juan de Lamilla',
 'Juan de Sevilla',
 'Juan de Vayas y Mota',
 'Juana de Sarria',
 'Justo de Cerna',
 'Laura María de Quirós',
 'Lorenzo de Lana',
 'Lucena del Puerto',
 'Lucena del Puerto, Convento de la Luz de Lucena del Puerto',
 'Luis Antonio Cabrera',
 'Luis Hermoso',
 'Maiorazgo de Cabrera',
 'Maiorazgo de Recuero',
 'Manuel Acevedo',
 'Manuel Caton',
 'Manuel Eusebio Varela',
 'Manuel Fernández',
 'Manuel Gil',
 'Manuel Morillo',
 'Manuel Ortiz',
 'Manuel de Medina',
 'Manuel de Saavedra',
 'Manuel de los Reyes',
 'Marquesa de Astorga',
 'Marquesa de La Motilla',
 'Marquesa de La Motilla, Convento de San Pablo de Sevilla',
 'Marqués de Astorga',
 'Marqués de Benamejí',
 'Marqués de Dos Hermanas',
 'Marqués de Gelo',
 'Marqués de La Fuente',
 'Marqués de Las Torres',
 'Marqués de Priego',
 'Marqués de Saltillo',
 'Marqués de Sauzo, Marquesa de Villa Nueva del Prado',
 'Marqués de Tablantes',
 'Marqués de Torralba',
 'Marqués de Torres',
 'Marqués de Valhermoso',
 'Marqués de Villa Franca',
 'Marqués de la Florida',
 'Marqués de la Fuente',
 'Marqués de la Villa',
 'María Beltrán',
 'María Lamilla',
 'María de Mendonza, Francisco Samariego',
 'Mateo del Castillo',
 'Miguel Roldán',
 'Miguel de Bustillo',
 'Miguel de Ribas',
 'Misericordia',
 'Misericordia de Sevilla',
 'Monasterio de la Cartuja de Jerez',
 'Niebla',
 'Nuño Carlos de Villacicencio',
 'Orden de Malta',
 'Patronato de Pelaez',
 'Patronato de Salas',
 'Pedro Alarán',
 'Pedro Briones',
 'Pedro Diego Esteban',
 'Pedro Manuel Motezuma',
 'Pedro Mendez',
 'Pedro Morales, Marqués de Caozo',
 'Pedro Ordiales',
 'Pedro Parreño',
 'Pedro Ponce',
 'Pedro Román and other unidentified individual',
 'Pilas',
 'Rafaela Millán',
 'Rociana del Condado',
 'Rodrigo Patronato',
 'Ronda',
 'Roque de Arena',
 'San Bartolomé de la Torre',
 'San Juan del Puerto',
 'Santa Olalla del Cala',
 'Sebastián Montilla',
 'Simón Naranjo',
 'Tereza de Campomanes,',
 'Trigueros',
 'Ubrique',
 'Umbrete',
 'Utrera',
 'Valverde del Camino',
 'Vicente García',
 'Vigario de El Castillo de las Guardas',
 'Vigário de Castilo de las Guardas',
 'Villa de Aznalcázar',
 'Villanueva de las Cruces',
 'Widow of Miguel Lamilla, Compañía de Jesus',
 'Zufre',
 'cabildo de la villa de Cala']

In [ ]:
# inspect tree species values
df['tree_species'].value_counts(dropna=False)

tree_species
pine                  194
holm oak              144
oak                    22
gall oak               21
NaN                    18
holm oak, gall oak      8
oak, gall oak           7
gall oak, cork oak      2
cork oak                2
olive                   1
Name: count, dtype: int64

In [ ]:
# create cleaned tree species column
df['tree_species_clean'] = (
    df['tree_species']
    .astype('string')
    .str.strip()
    .str.lower()
    .str.replace(r'\s+', ' ', regex=True)
)

In [ ]:
# inspect cleaned tree species values
df['tree_species_clean'].value_counts(dropna=False)

tree_species_clean
pine                  194
holm oak              144
oak                    22
gall oak               21
<NA>                   18
holm oak, gall oak      8
oak, gall oak           7
gall oak, cork oak      2
cork oak                2
olive                   1
Name: count, dtype: int64[pyarrow]

In [ ]:
# inspect cleaned tree quantity column
df['tree_quantity_clean'].describe()

count     404.000000
mean      164.066832
std       445.593276
min         1.000000
25%         5.000000
50%        25.000000
75%       120.750000
max      4198.000000
Name: tree_quantity_clean, dtype: float64

In [ ]:
# inspect all unique cleaned tree quantity values
sorted(df['tree_quantity_clean'].dropna().unique())

[np.float64(1.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(6.0),
 np.float64(7.0),
 np.float64(8.0),
 np.float64(9.0),
 np.float64(10.0),
 np.float64(11.0),
 np.float64(12.0),
 np.float64(13.0),
 np.float64(14.0),
 np.float64(15.0),
 np.float64(16.0),
 np.float64(17.0),
 np.float64(18.0),
 np.float64(19.0),
 np.float64(20.0),
 np.float64(21.0),
 np.float64(22.0),
 np.float64(23.0),
 np.float64(24.0),
 np.float64(25.0),
 np.float64(26.0),
 np.float64(27.0),
 np.float64(28.0),
 np.float64(29.0),
 np.float64(30.0),
 np.float64(31.0),
 np.float64(32.0),
 np.float64(33.0),
 np.float64(34.0),
 np.float64(36.0),
 np.float64(37.0),
 np.float64(39.0),
 np.float64(40.0),
 np.float64(41.0),
 np.float64(43.0),
 np.float64(44.0),
 np.float64(46.0),
 np.float64(47.0),
 np.float64(48.0),
 np.float64(50.0),
 np.float64(51.0),
 np.float64(53.0),
 np.float64(54.0),
 np.float64(55.0),
 np.float64(56.0),
 np.float64(57.0),
 np.float64(59.0),
 np.float64(60.0),
 np.float64(61.0),
 np.float64(63.0),
 np.float64(64.0),
 np.float64(65.0),
 np.float64(66.0),
 np.float64(69.0),
 np.float64(70.0),
 np.float64(71.0),
 np.float64(72.0),
 np.float64(73.0),
 np.float64(74.0),
 np.float64(78.0),
 np.float64(80.0),
 np.float64(82.0),
 np.float64(83.0),
 np.float64(87.0),
 np.float64(88.0),
 np.float64(91.0),
 np.float64(95.0),
 np.float64(96.0),
 np.float64(98.0),
 np.float64(99.0),
 np.float64(100.0),
 np.float64(102.0),
 np.float64(103.0),
 np.float64(104.0),
 np.float64(108.0),
 np.float64(109.0),
 np.float64(119.0),
 np.float64(120.0),
 np.float64(123.0),
 np.float64(130.0),
 np.float64(134.0),
 np.float64(137.0),
 np.float64(147.0),
 np.float64(150.0),
 np.float64(160.0),
 np.float64(167.0),
 np.float64(170.0),
 np.float64(186.0),
 np.float64(188.0),
 np.float64(192.0),
 np.float64(197.0),
 np.float64(200.0),
 np.float64(201.0),
 np.float64(204.0),
 np.float64(208.0),
 np.float64(209.0),
 np.float64(210.0),
 np.float64(211.0),
 np.float64(213.0),
 np.float64(219.0),
 np.float64(220.0),
 np.float64(230.0),
 np.float64(231.0),
 np.float64(233.0),
 np.float64(234.0),
 np.float64(237.0),
 np.float64(238.0),
 np.float64(240.0),
 np.float64(245.0),
 np.float64(250.0),
 np.float64(266.0),
 np.float64(282.0),
 np.float64(286.0),
 np.float64(287.0),
 np.float64(294.0),
 np.float64(298.0),
 np.float64(300.0),
 np.float64(310.0),
 np.float64(319.0),
 np.float64(320.0),
 np.float64(332.0),
 np.float64(338.0),
 np.float64(341.0),
 np.float64(346.0),
 np.float64(360.0),
 np.float64(370.0),
 np.float64(372.0),
 np.float64(383.0),
 np.float64(384.0),
 np.float64(400.0),
 np.float64(448.0),
 np.float64(494.0),
 np.float64(533.0),
 np.float64(559.0),
 np.float64(560.0),
 np.float64(582.0),
 np.float64(599.0),
 np.float64(605.0),
 np.float64(622.0),
 np.float64(668.0),
 np.float64(851.0),
 np.float64(859.0),
 np.float64(898.0),
 np.float64(1113.0),
 np.float64(1165.0),
 np.float64(1300.0),
 np.float64(1406.0),
 np.float64(1457.0),
 np.float64(1645.0),
 np.float64(2087.0),
 np.float64(2120.0),
 np.float64(2847.0),
 np.float64(2986.0),
 np.float64(3150.0),
 np.float64(3593.0),
 np.float64(4198.0)]

In [ ]:
# inspect felling period values
df['felling_period'].value_counts(dropna=False)

felling_period
1749-1751    119
1749-1750    100
1748-1749     74
1749          38
1751          37
1750          19
1748-1751     14
1748-1750      8
1750-1751      4
1749-1752      2
1749-1753      1
1749-1754      1
1749-1755      1
1749-1756      1
Name: count, dtype: int64

In [ ]:
# standardize incorrect felling period ranges
df['felling_period'] = df['felling_period'].replace({
    '1749-1752': '1749-1751',
    '1749-1753': '1749-1751',
    '1749-1754': '1749-1751',
    '1749-1755': '1749-1751',
    '1749-1756': '1749-1751'
})

In [ ]:
# inspect felling period values again
df['felling_period'].value_counts(dropna=False)

felling_period
1749-1751    125
1749-1750    100
1748-1749     74
1749          38
1751          37
1750          19
1748-1751     14
1748-1750      8
1750-1751      4
Name: count, dtype: int64

In [ ]:
# correct one specific felling period value
df.loc[
    (df['felling_period'] == '1758-1750') &
    (df['municipality_clean'] == 'Hinojos') &
    (df['tree_quantity_clean'] == 211.0),
    'felling_period'
] = '1748-1751'

In [ ]:
# inspect felling period values again
df['felling_period'].value_counts(dropna=False)

felling_period
1749-1751    125
1749-1750    100
1748-1749     74
1749          38
1751          37
1750          19
1748-1751     14
1748-1750      8
1750-1751      4
Name: count, dtype: int64

In [ ]:
# inspect the corrected Hinojos row
df.loc[
    (df['municipality_clean'] == 'Hinojos') &
    (df['tree_quantity_clean'] == 211.0)
]

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean
141,1748-1750,Hinojos,Hinojos,NaN,NaN,Hinojos,Huelva,comunal,Hinojos,pine,211,211.0,NaN,NaN,Huelva,Hinojos,comunal,Hinojos,pine

In [ ]:
# correct the specific Hinojos row
df.loc[
    (df['municipality_clean'] == 'Hinojos') &
    (df['tree_quantity_clean'] == 211.0) &
    (df['felling_period'] == '1748-1750'),
    'felling_period'
] = '1748-1751'

In [ ]:
# inspect the corrected Hinojos row again
df.loc[
    (df['municipality_clean'] == 'Hinojos') &
    (df['tree_quantity_clean'] == 211.0)
]

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean
141,1748-1751,Hinojos,Hinojos,NaN,NaN,Hinojos,Huelva,comunal,Hinojos,pine,211,211.0,NaN,NaN,Huelva,Hinojos,comunal,Hinojos,pine

In [ ]:
# inspect source toponymy values
df['felling_toponymy_source'].value_counts(dropna=False)

felling_toponymy_source
Utrera        53
Almonte       30
Hinojos       22
Aznalcázar     8
Marchena       7
              ..
Valdíos        1
Cañuelo        1
La Suerte      1
Patronato      1
Baldios        1
Name: count, Length: 219, dtype: int64

In [ ]:
# inspect all unique source toponymy values alphabetically
sorted(df['felling_toponymy_source'].dropna().unique())

['\nZelada',
 'Alcornocal',
 'Almonte',
 'Arahal',
 'Armuña',
 'Arroyo del Moro',
 'Arroyo del Puerco',
 'Atrera',
 'Aznalcázar',
 'Balcargado',
 'Baldios',
 'Baldíos de Jimena',
 'Balzequilla',
 'Barranco',
 'Barranco de la Fantasma',
 'Bañuelos',
 'Benacazón',
 'Benahú',
 'Boca Dulce',
 'Bollullos',
 'Boyal de Villa Rassa',
 'Boyal de Vonares',
 'Breña de la Jara',
 'Breña del Água',
 'Buqueos de Pulga',
 'Cala',
 'Campo de las Encinas',
 'Candón',
 'Cardela',
 'Casa de Sierra',
 'Castellar',
 'Cavezadas del Guadarranque',
 'Cañada',
 'Cañuelo',
 'Chaparral',
 'Charco de los Furones',
 'Chorreadero',
 'Chucena',
 'Cortijera',
 'Crespín',
 'Cuesta de Huevo Duro',
 'Dehesa Vollar',
 'Dehesa de Alcalá del Valle',
 'Dehesa de Algarrobo',
 'Dehesa de Aljobar',
 'Dehesa de Alosno',
 'Dehesa de Benacazón',
 'Dehesa de Boyar',
 'Dehesa de Boyar de  Rusiana',
 'Dehesa de Buenas Noches',
 'Dehesa de Castillo de las Guardas',
 'Dehesa de Charena',
 'Dehesa de Chillas',
 'Dehesa de Collera',
 'Dehesa de Céspedes y Molinos',
 'Dehesa de Espechilla',
 'Dehesa de Fazana',
 'Dehesa de Garruchena',
 'Dehesa de Gato',
 'Dehesa de Genil',
 'Dehesa de Juncoso',
 'Dehesa de Lerena',
 'Dehesa de Luzena',
 'Dehesa de Molino de los Zéspedes',
 'Dehesa de Montanina',
 'Dehesa de Montañina',
 'Dehesa de Nava Matrera',
 'Dehesa de Pasada Blanca',
 'Dehesa de Paternina',
 'Dehesa de Pilas',
 'Dehesa de Pormedias',
 'Dehesa de Purchena',
 'Dehesa de Remuñana',
 'Dehesa de Robaina',
 'Dehesa de San Bartolomé',
 'Dehesa de Santillan',
 'Dehesa de Santillán',
 'Dehesa de Torralba',
 'Dehesa de Torre de Palencia',
 'Dehesa de Torre de Quadros',
 'Dehesa de Torres',
 'Dehesa de Trigueros',
 'Dehesa de Valberde del Camino',
 'Dehesa de Venacazon',
 'Dehesa de Venacazon / Boyal de Venacazon',
 'Dehesa de Venaxiar',
 'Dehesa de el Zerro',
 'Dehesa de la Goleta',
 'Dehesa de la Granadilla',
 'Dehesa de la Hoya de la Muger',
 'Dehesa de la Iguera',
 'Dehesa de la Parrilla',
 'Dehesa de las Cruces',
 'Dehesa de las Navas',
 'Dehesa del Río',
 'Dehesa del Tomillo',
 'Diego Duro',
 'Dos Hermanas',
 'El Bosque',
 'El Canchal',
 'El Caosso',
 'El Corso',
 'El Enimigo',
 'El Gamero',
 'El Molino',
 'El Navazo',
 'El Palancón',
 'El Palero',
 'El Rosal',
 'Esparragosilla',
 'Espartinas',
 'Espossas',
 'Exes de Moracha',
 'Gamín Bajo, Gamín Alto,Argamis Alto ',
 'Garganta de Millán',
 'Garganta de la Tala',
 'Garganta de las Palas',
 'Garganta del Artillero',
 'Garruchena',
 'Gelo',
 'Genis',
 'Gradillos',
 'Granadilla',
 'Hinojos',
 'Hoya del Pinar',
 'Huertas de Benahoma',
 'Huevar',
 'Jarama',
 'Jaramilla',
 'Jarda',
 'La Dehesa',
 'La Jardilla',
 'La Lombarda',
 'La Montañesa',
 'La Nobenera',
 'La Suerte',
 'La Suerte del Valle',
 'La Thenienta',
 'La Tiessa',
 'La Umbría',
 'La Zierba',
 'Labradillo',
 'Lajuela',
 'Lanchas',
 'Las Corchas',
 'Lentiscal',
 'Linde de Remuñana',
 'Loma de la Peña',
 'Lopas',
 'Los Cercados',
 'Los Gavilanes',
 'Los Graneros',
 'Los Millares',
 'Los Molares',
 'Los Molinos',
 'Marchena',
 'Marrufo',
 'Menina',
 'Mesquitilla',
 'Miraflores',
 'Moguer',
 'Mojin',
 'Monte de la Gitana',
 'Monte de la Zarza',
 'Monte de los Peregrinos',
 'Monte del Berrueco',
 'Monte del Boyar',
 'Moracha Alta',
 'Moros',
 'Olivares',
 'Palma Gallarda',
 'Pantorilla',
 'Paradas',
 'Patronato',
 'Pilas',
 'Pinal de la Plata',
 'Posteruelos',
 'Pozo del Zierbo',
 'Puerto de Argamazón',
 'Puerto de las Encinas',
 'Puñana',
 'Quema',
 'Rebujena la Alta',
 'Recuero',
 'Ronda',
 'Ruissa',
 'Salvador Díaz',
 'San Gines',
 'San Julian',
 'Santa María de Guadalupe',
 'Santa María de Guadalupe / El Bosque',
 'Santa Olaia',
 'Santa Olalla del Cala',
 'Sauceda',
 'Seresuela de Humbrete',
 'Sevilla',
 'Sierra de Jerez',
 'Suerte de Quintanilla',
 'Suerte del Saltillo',
 'Tocina',
 'Toconal',
 'Torre de Quadros',
 'Torre de las Arcas',
 'Torrequemada',
 'Torres',
 'Tronco',
 'Ubrique',
 'Umbrete',
 'Utrera',
 'Valdíos',
 'Vegas de Juan Peon',
 'Ventanas',
 'Vera Cruz',
 'Vera de Pedro Cano',
 'Villa Gordo',
 'Villa Nueva del Ariscal',
 'Villalba',
 'Xerez',
 'Zerro del Almendro']

In [ ]:
# remove line breaks and extra spaces from source toponymy column
df['felling_toponymy_source'] = (
    df['felling_toponymy_source']
    .str.replace('\n', ' ', regex=False)
    .str.strip()
)

In [ ]:
# inspect all unique source toponymy values alphabetically
sorted(df['felling_toponymy_source'].dropna().unique())

['Alcornocal',
 'Almonte',
 'Arahal',
 'Armuña',
 'Arroyo del Moro',
 'Arroyo del Puerco',
 'Atrera',
 'Aznalcázar',
 'Balcargado',
 'Baldios',
 'Baldíos de Jimena',
 'Balzequilla',
 'Barranco',
 'Barranco de la Fantasma',
 'Bañuelos',
 'Benacazón',
 'Benahú',
 'Boca Dulce',
 'Bollullos',
 'Boyal de Villa Rassa',
 'Boyal de Vonares',
 'Breña de la Jara',
 'Breña del Água',
 'Buqueos de Pulga',
 'Cala',
 'Campo de las Encinas',
 'Candón',
 'Cardela',
 'Casa de Sierra',
 'Castellar',
 'Cavezadas del Guadarranque',
 'Cañada',
 'Cañuelo',
 'Chaparral',
 'Charco de los Furones',
 'Chorreadero',
 'Chucena',
 'Cortijera',
 'Crespín',
 'Cuesta de Huevo Duro',
 'Dehesa Vollar',
 'Dehesa de Alcalá del Valle',
 'Dehesa de Algarrobo',
 'Dehesa de Aljobar',
 'Dehesa de Alosno',
 'Dehesa de Benacazón',
 'Dehesa de Boyar',
 'Dehesa de Boyar de  Rusiana',
 'Dehesa de Buenas Noches',
 'Dehesa de Castillo de las Guardas',
 'Dehesa de Charena',
 'Dehesa de Chillas',
 'Dehesa de Collera',
 'Dehesa de Céspedes y Molinos',
 'Dehesa de Espechilla',
 'Dehesa de Fazana',
 'Dehesa de Garruchena',
 'Dehesa de Gato',
 'Dehesa de Genil',
 'Dehesa de Juncoso',
 'Dehesa de Lerena',
 'Dehesa de Luzena',
 'Dehesa de Molino de los Zéspedes',
 'Dehesa de Montanina',
 'Dehesa de Montañina',
 'Dehesa de Nava Matrera',
 'Dehesa de Pasada Blanca',
 'Dehesa de Paternina',
 'Dehesa de Pilas',
 'Dehesa de Pormedias',
 'Dehesa de Purchena',
 'Dehesa de Remuñana',
 'Dehesa de Robaina',
 'Dehesa de San Bartolomé',
 'Dehesa de Santillan',
 'Dehesa de Santillán',
 'Dehesa de Torralba',
 'Dehesa de Torre de Palencia',
 'Dehesa de Torre de Quadros',
 'Dehesa de Torres',
 'Dehesa de Trigueros',
 'Dehesa de Valberde del Camino',
 'Dehesa de Venacazon',
 'Dehesa de Venacazon / Boyal de Venacazon',
 'Dehesa de Venaxiar',
 'Dehesa de el Zerro',
 'Dehesa de la Goleta',
 'Dehesa de la Granadilla',
 'Dehesa de la Hoya de la Muger',
 'Dehesa de la Iguera',
 'Dehesa de la Parrilla',
 'Dehesa de las Cruces',
 'Dehesa de las Navas',
 'Dehesa del Río',
 'Dehesa del Tomillo',
 'Diego Duro',
 'Dos Hermanas',
 'El Bosque',
 'El Canchal',
 'El Caosso',
 'El Corso',
 'El Enimigo',
 'El Gamero',
 'El Molino',
 'El Navazo',
 'El Palancón',
 'El Palero',
 'El Rosal',
 'Esparragosilla',
 'Espartinas',
 'Espossas',
 'Exes de Moracha',
 'Gamín Bajo, Gamín Alto,Argamis Alto',
 'Garganta de Millán',
 'Garganta de la Tala',
 'Garganta de las Palas',
 'Garganta del Artillero',
 'Garruchena',
 'Gelo',
 'Genis',
 'Gradillos',
 'Granadilla',
 'Hinojos',
 'Hoya del Pinar',
 'Huertas de Benahoma',
 'Huevar',
 'Jarama',
 'Jaramilla',
 'Jarda',
 'La Dehesa',
 'La Jardilla',
 'La Lombarda',
 'La Montañesa',
 'La Nobenera',
 'La Suerte',
 'La Suerte del Valle',
 'La Thenienta',
 'La Tiessa',
 'La Umbría',
 'La Zierba',
 'Labradillo',
 'Lajuela',
 'Lanchas',
 'Las Corchas',
 'Lentiscal',
 'Linde de Remuñana',
 'Loma de la Peña',
 'Lopas',
 'Los Cercados',
 'Los Gavilanes',
 'Los Graneros',
 'Los Millares',
 'Los Molares',
 'Los Molinos',
 'Marchena',
 'Marrufo',
 'Menina',
 'Mesquitilla',
 'Miraflores',
 'Moguer',
 'Mojin',
 'Monte de la Gitana',
 'Monte de la Zarza',
 'Monte de los Peregrinos',
 'Monte del Berrueco',
 'Monte del Boyar',
 'Moracha Alta',
 'Moros',
 'Olivares',
 'Palma Gallarda',
 'Pantorilla',
 'Paradas',
 'Patronato',
 'Pilas',
 'Pinal de la Plata',
 'Posteruelos',
 'Pozo del Zierbo',
 'Puerto de Argamazón',
 'Puerto de las Encinas',
 'Puñana',
 'Quema',
 'Rebujena la Alta',
 'Recuero',
 'Ronda',
 'Ruissa',
 'Salvador Díaz',
 'San Gines',
 'San Julian',
 'Santa María de Guadalupe',
 'Santa María de Guadalupe / El Bosque',
 'Santa Olaia',
 'Santa Olalla del Cala',
 'Sauceda',
 'Seresuela de Humbrete',
 'Sevilla',
 'Sierra de Jerez',
 'Suerte de Quintanilla',
 'Suerte del Saltillo',
 'Tocina',
 'Toconal',
 'Torre de Quadros',
 'Torre de las Arcas',
 'Torrequemada',
 'Torres',
 'Tronco',
 'Ubrique',
 'Umbrete',
 'Utrera',
 'Valdíos',
 'Vegas de Juan Peon',
 'Ventanas',
 'Vera Cruz',
 'Vera de Pedro Cano',
 'Villa Gordo',
 'Villa Nueva del Ariscal',
 'Villalba',
 'Xerez',
 'Zelada',
 'Zerro del Almendro']

In [ ]:
# inspect MTN25 toponymy values
df['felling_toponymy_MTN25'].value_counts(dropna=False)

felling_toponymy_MTN25
Utrera              53
Almonte             30
NaN                 22
Hinojos             22
Aznalcázar           8
                    ..
Dehesa de Puyana     1
Casa Sierra          1
El Badío             1
El Cañuelo           1
Patronato            1
Name: count, Length: 194, dtype: int64

In [ ]:
# inspect all unique MTN25 toponymy values alphabetically
sorted(df['felling_toponymy_MTN25'].dropna().unique())

[' Las Lanchas ',
 'Alcornocal',
 'Almonte',
 'Arahal',
 'Arroyo de las Palas',
 'Arroyo del Artillero',
 'Arroyo del Moro',
 'Arroyo del Palerillo Bajo ',
 'Arroyo del Puerco',
 'Atrera',
 'Aznalcázar',
 'Barranco',
 'Benacazón',
 'Benahoma',
 'Benajiar',
 'Benajiar ',
 'Bollullos',
 'Breña del Água',
 'Buenas Noches Vieja',
 'Cala',
 'Camino de la Dehesa',
 'Campo de las Encinas',
 'Cardela ',
 'Casa Sierra',
 'Casa de Aljóbar',
 'Casa de Diego Duro ',
 'Casa del Gamero ',
 'Casas del Palancar ',
 'Cañada de los Charcos',
 'Cerro de Breña Honda, ',
 'Cerro de Robaina',
 'Cerro del Almendro',
 'Cerro del Enimigo ',
 'Chaparral',
 'Charenas',
 'Chorreadero',
 'Chucena',
 'Collera',
 'Cortijera',
 'Cortijo de Chilla',
 'Cortijo de Chillas',
 'Cortijo de Quema',
 'Cortijo de Veracruz',
 'Cortijo de la Montañesa',
 'Cortijo de la Parrilla ',
 'Cortijo de los Molinos',
 'Crespín',
 'Crispín',
 'Cueva de la Gitana ',
 'Cándon',
 'Dehesa Boyal',
 'Dehesa de Abajo',
 'Dehesa de Arriba',
 'Dehesa de Benahú ',
 'Dehesa de Charco de los Hurones',
 'Dehesa de Espechilla',
 'Dehesa de Fasana',
 'Dehesa de Gamí ',
 'Dehesa de Garruchena',
 'Dehesa de Gelo',
 'Dehesa de Lerena',
 'Dehesa de Lopaz',
 'Dehesa de Marrufo',
 'Dehesa de Navamatrera ',
 'Dehesa de Pasada Blanca',
 'Dehesa de Paternina',
 'Dehesa de Pilas',
 'Dehesa de Purchena',
 'Dehesa de Puyana',
 'Dehesa de Remuñana',
 'Dehesa de Romuñana',
 'Dehesa de Santa María del Río',
 'Dehesa de Torrecuadros',
 'Dehesa de la Jarda ',
 'Dehesa de la Parrilla',
 'Dehesa de las Esposas',
 'Dehesa de los Machos',
 'Dehesa del Castillo',
 'Dehesa del Jarama',
 'Dehesa del Jarramilla',
 'Dehesas',
 'Dos Hermanas',
 'El Badío',
 'El Berrueco',
 'El Bosque',
 'El Boyal',
 'El Cadoso',
 'El Canchal',
 'El Canchal ',
 'El Cañuelo',
 'El Chaparral',
 'El Corzo',
 'El Gato',
 'El Juncoso',
 'El Lentiscar',
 'El Molino',
 'El Navazo',
 'El Pinar ',
 'El Recuero',
 'El Rosalejo',
 'El Toconal',
 'Espartinas',
 'Fuente de la Hoya de la Mujer ',
 'Gato',
 'Hacienda de Genis',
 'Hacienda de Genis  ',
 'Hacienda de Torralba',
 'Hacienda de Torres',
 'Hacienda de la Cierva',
 'Hinojos',
 'Huevar',
 'Jeréz de la Frontera',
 'La Almuñia',
 'La Boyal ',
 'La Celada',
 'La Cuesta',
 'La Dehesa',
 'La Dehesilla',
 'La Esparragosilla',
 'La Fantasma ',
 'La Goleta',
 'La Granadilla',
 'La Jardilla ',
 'La Lombarda',
 'La Mezquitilla ',
 'La Mogea de la Tala ',
 'La Mohína',
 'La Montañina',
 'La Moracha',
 'La Novenera',
 'La Plata',
 'La Ruiza ',
 'La Sauceda',
 'La Suerte',
 'La Tenienta',
 'La Tiesa',
 'La Umbría',
 'Las Corchas',
 'Las Torres',
 'Las Torres ',
 'Las Vaquerizas',
 'Las Vaquerizas ',
 'Las Vegas',
 'Loma de la Peña',
 'Loma de la Pulga',
 'Los Cercados',
 'Los Ejes',
 'Los Gavilanes',
 'Los Graneros',
 'Los Labradillos',
 'Los Millares',
 'Los Olivos',
 'Los Pradillos',
 'Los Tomillos',
 'Los Ventanales',
 'Majada de las Navas ',
 'Marchena',
 'Medina',
 'Millán',
 'Miraflores',
 'Moguer',
 'Palma Gallarda',
 'Pantorilla',
 'Paradas',
 'Patronato',
 'Pilas',
 'Posteruelos',
 'Pozo Dulce',
 'Puerto de la Encina',
 'Puerto del Argamazón',
 'Quintanilla',
 'Rebujena Alta',
 'Ronda',
 'Roza de Bañuelos',
 'Río Guardarranque ',
 'Salvador Díaz',
 'San Ginés',
 'Santa Olalla del Cala',
 'Santillán',
 'Sevilla',
 'Suerte del Marqués',
 'Tocina',
 'Torre de las Arcas',
 'Torrequemada ',
 'Ubrique',
 'Umbrete',
 'Utrera',
 'Valdejulian',
 'Valquemado ',
 'Vera de Pedro Cano',
 'Villa Gordo',
 'Villa Nueva del Ariscal',
 'Villalba del Alcor ']

In [ ]:
# apply manual corrections to MTN25 toponymy values
df['felling_toponymy_MTN25_clean'] = df['felling_toponymy_MTN25_clean'].replace({

    ' Las Lanchas ': 'Las Lanchas',
    'Arroyo del Palerillo Bajo ': 'Arroyo del Palerillo Bajo',
    'Benajiar ': 'Benajiar',
    'Cardela ': 'Cardela',
    'Casa de Diego Duro ': 'Casa de Diego Duro',
    'Casa del Gamero ': 'Casa del Gamero',
    'Casas del Palancar ': 'Casas del Palancar',
    'Cerro de Breña Honda, ': 'Cerro de Breña Honda',
    'Cerro del Enimigo ': 'Cerro del Enimigo',
    'Cortijo de Chillas': 'Cortijo de Chilla',
    'Cortijo de la Parrilla ': 'Cortijo de la Parrilla',
    'Crispín': 'Crespín',
    'Cueva de la Gitana ': 'Cueva de la Gitana',
    'Cándon': 'Candón',
    'Dehesa de Benahú ': 'Dehesa de Benahú',
    'Dehesa de Gamí ': 'Dehesa de Gamí',
    'Dehesa de Navamatrera ': 'Dehesa de Navamatrera',
    'Dehesa de Romuñana': 'Dehesa de Remuñana',
    'Dehesa de la Jarda ': 'Dehesa de la Jarda',
    'El Canchal ': 'El Canchal',
    'El Pinar ': 'El Pinar',
    'Fuente de la Hoya de la Mujer ': 'Fuente de la Hoya de la Mujer',
    'Hacienda de Genis  ': 'Hacienda de Genis',
    'Huevar': 'Huévar',
    'Jeréz de la Frontera': 'Jerez de la Frontera',
    'La Boyal ': 'La Boyal',
    'La Fantasma ': 'La Fantasma',
    'La Jardilla ': 'La Jardilla',
    'La Mezquitilla ': 'La Mezquitilla',
    'La Mogea de la Tala ': 'La Mogea de la Tala',
    'La Ruiza ': 'La Ruiza',
    'Las Torres ': 'Las Torres',
    'Las Vaquerizas ': 'Las Vaquerizas',
    'Majada de las Navas ': 'Majada de las Navas',
    'Río Guardarranque ': 'Río Guardarranque',
    'Torrequemada ': 'Torrequemada',
    'Valquemado ': 'Valquemado',
    'Villa Nueva del Ariscal': 'Villanueva del Ariscal',
    'Villalba del Alcor ': 'Villalba del Alcor'
})

KeyError: 'felling_toponymy_MTN25_clean'

In [ ]:
# create cleaned MTN25 toponymy column
df['felling_toponymy_MTN25_clean'] = (
    df['felling_toponymy_MTN25']
    .astype('string')
    .str.replace('\n', ' ', regex=False)
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

In [ ]:
# apply manual corrections to MTN25 toponymy values
df['felling_toponymy_MTN25_clean'] = df['felling_toponymy_MTN25_clean'].replace({

    ' Las Lanchas ': 'Las Lanchas',
    'Arroyo del Palerillo Bajo ': 'Arroyo del Palerillo Bajo',
    'Benajiar ': 'Benajiar',
    'Cardela ': 'Cardela',
    'Casa de Diego Duro ': 'Casa de Diego Duro',
    'Casa del Gamero ': 'Casa del Gamero',
    'Casas del Palancar ': 'Casas del Palancar',
    'Cerro de Breña Honda, ': 'Cerro de Breña Honda',
    'Cerro del Enimigo ': 'Cerro del Enimigo',
    'Cortijo de Chillas': 'Cortijo de Chilla',
    'Cortijo de la Parrilla ': 'Cortijo de la Parrilla',
    'Crispín': 'Crespín',
    'Cueva de la Gitana ': 'Cueva de la Gitana',
    'Cándon': 'Candón',
    'Dehesa de Benahú ': 'Dehesa de Benahú',
    'Dehesa de Gamí ': 'Dehesa de Gamí',
    'Dehesa de Navamatrera ': 'Dehesa de Navamatrera',
    'Dehesa de Romuñana': 'Dehesa de Remuñana',
    'Dehesa de la Jarda ': 'Dehesa de la Jarda',
    'El Canchal ': 'El Canchal',
    'El Pinar ': 'El Pinar',
    'Fuente de la Hoya de la Mujer ': 'Fuente de la Hoya de la Mujer',
    'Hacienda de Genis  ': 'Hacienda de Genis',
    'Huevar': 'Huévar',
    'Jeréz de la Frontera': 'Jerez de la Frontera',
    'La Boyal ': 'La Boyal',
    'La Fantasma ': 'La Fantasma',
    'La Jardilla ': 'La Jardilla',
    'La Mezquitilla ': 'La Mezquitilla',
    'La Mogea de la Tala ': 'La Mogea de la Tala',
    'La Ruiza ': 'La Ruiza',
    'Las Torres ': 'Las Torres',
    'Las Vaquerizas ': 'Las Vaquerizas',
    'Majada de las Navas ': 'Majada de las Navas',
    'Río Guardarranque ': 'Río Guardarranque',
    'Torrequemada ': 'Torrequemada',
    'Valquemado ': 'Valquemado',
    'Villa Nueva del Ariscal': 'Villanueva del Ariscal',
    'Villalba del Alcor ': 'Villalba del Alcor'
})

In [ ]:
# inspect cleaned MTN25 toponymy values
sorted(df['felling_toponymy_MTN25_clean'].dropna().unique())

['Alcornocal',
 'Almonte',
 'Arahal',
 'Arroyo de las Palas',
 'Arroyo del Artillero',
 'Arroyo del Moro',
 'Arroyo del Palerillo Bajo',
 'Arroyo del Puerco',
 'Atrera',
 'Aznalcázar',
 'Barranco',
 'Benacazón',
 'Benahoma',
 'Benajiar',
 'Bollullos',
 'Breña del Água',
 'Buenas Noches Vieja',
 'Cala',
 'Camino de la Dehesa',
 'Campo de las Encinas',
 'Candón',
 'Cardela',
 'Casa Sierra',
 'Casa de Aljóbar',
 'Casa de Diego Duro',
 'Casa del Gamero',
 'Casas del Palancar',
 'Cañada de los Charcos',
 'Cerro de Breña Honda,',
 'Cerro de Robaina',
 'Cerro del Almendro',
 'Cerro del Enimigo',
 'Chaparral',
 'Charenas',
 'Chorreadero',
 'Chucena',
 'Collera',
 'Cortijera',
 'Cortijo de Chilla',
 'Cortijo de Quema',
 'Cortijo de Veracruz',
 'Cortijo de la Montañesa',
 'Cortijo de la Parrilla',
 'Cortijo de los Molinos',
 'Crespín',
 'Cueva de la Gitana',
 'Dehesa Boyal',
 'Dehesa de Abajo',
 'Dehesa de Arriba',
 'Dehesa de Benahú',
 'Dehesa de Charco de los Hurones',
 'Dehesa de Espechilla',
 'Dehesa de Fasana',
 'Dehesa de Gamí',
 'Dehesa de Garruchena',
 'Dehesa de Gelo',
 'Dehesa de Lerena',
 'Dehesa de Lopaz',
 'Dehesa de Marrufo',
 'Dehesa de Navamatrera',
 'Dehesa de Pasada Blanca',
 'Dehesa de Paternina',
 'Dehesa de Pilas',
 'Dehesa de Purchena',
 'Dehesa de Puyana',
 'Dehesa de Remuñana',
 'Dehesa de Santa María del Río',
 'Dehesa de Torrecuadros',
 'Dehesa de la Jarda',
 'Dehesa de la Parrilla',
 'Dehesa de las Esposas',
 'Dehesa de los Machos',
 'Dehesa del Castillo',
 'Dehesa del Jarama',
 'Dehesa del Jarramilla',
 'Dehesas',
 'Dos Hermanas',
 'El Badío',
 'El Berrueco',
 'El Bosque',
 'El Boyal',
 'El Cadoso',
 'El Canchal',
 'El Cañuelo',
 'El Chaparral',
 'El Corzo',
 'El Gato',
 'El Juncoso',
 'El Lentiscar',
 'El Molino',
 'El Navazo',
 'El Pinar',
 'El Recuero',
 'El Rosalejo',
 'El Toconal',
 'Espartinas',
 'Fuente de la Hoya de la Mujer',
 'Gato',
 'Hacienda de Genis',
 'Hacienda de Torralba',
 'Hacienda de Torres',
 'Hacienda de la Cierva',
 'Hinojos',
 'Huévar',
 'Jerez de la Frontera',
 'La Almuñia',
 'La Boyal',
 'La Celada',
 'La Cuesta',
 'La Dehesa',
 'La Dehesilla',
 'La Esparragosilla',
 'La Fantasma',
 'La Goleta',
 'La Granadilla',
 'La Jardilla',
 'La Lombarda',
 'La Mezquitilla',
 'La Mogea de la Tala',
 'La Mohína',
 'La Montañina',
 'La Moracha',
 'La Novenera',
 'La Plata',
 'La Ruiza',
 'La Sauceda',
 'La Suerte',
 'La Tenienta',
 'La Tiesa',
 'La Umbría',
 'Las Corchas',
 'Las Lanchas',
 'Las Torres',
 'Las Vaquerizas',
 'Las Vegas',
 'Loma de la Peña',
 'Loma de la Pulga',
 'Los Cercados',
 'Los Ejes',
 'Los Gavilanes',
 'Los Graneros',
 'Los Labradillos',
 'Los Millares',
 'Los Olivos',
 'Los Pradillos',
 'Los Tomillos',
 'Los Ventanales',
 'Majada de las Navas',
 'Marchena',
 'Medina',
 'Millán',
 'Miraflores',
 'Moguer',
 'Palma Gallarda',
 'Pantorilla',
 'Paradas',
 'Patronato',
 'Pilas',
 'Posteruelos',
 'Pozo Dulce',
 'Puerto de la Encina',
 'Puerto del Argamazón',
 'Quintanilla',
 'Rebujena Alta',
 'Ronda',
 'Roza de Bañuelos',
 'Río Guardarranque',
 'Salvador Díaz',
 'San Ginés',
 'Santa Olalla del Cala',
 'Santillán',
 'Sevilla',
 'Suerte del Marqués',
 'Tocina',
 'Torre de las Arcas',
 'Torrequemada',
 'Ubrique',
 'Umbrete',
 'Utrera',
 'Valdejulian',
 'Valquemado',
 'Vera de Pedro Cano',
 'Villa Gordo',
 'Villalba del Alcor',
 'Villanueva del Ariscal']

In [ ]:
# count missing values in MTN25 toponymy column
df['felling_toponymy_MTN25_clean'].isna().sum()

np.int64(22)

In [ ]:
# inspect rows with missing MTN25 toponymy
df.loc[df['felling_toponymy_MTN25_clean'].isna(), [
    'felling_toponymy_source',
    'municipality_clean',
    'province_clean',
    'latitude_clean',
    'longitude_clean'
]]

,felling_toponymy_source,municipality_clean,province_clean,latitude_clean,longitude_clean
25,Castellar,Castellar de la Frontera,Cádiz,NaN,NaN
26,Dehesa de Alcalá del Valle,Alcalá del Valle,Cádiz,NaN,NaN
68,Baldíos de Jimena,Jimena de la Frontera,Cádiz,NaN,NaN
74,Tronco,Jimena de la Frontera,Cádiz,NaN,NaN
75,Moros,Jimena de la Frontera,Cádiz,NaN,NaN
76,Lajuela,Jimena de la Frontera,Cádiz,NaN,NaN
77,Monte de la Zarza,Jimena de la Frontera,Cádiz,NaN,NaN
78,Sierra de Jerez,Jerez de la Frontera,Cádiz,NaN,NaN
95,Dehesa de Molino de los Zéspedes,Carrión de los Céspedes,Sevilla,NaN,NaN
116,Dehesa de Torre de Palencia,Huelva,Huelva,NaN,NaN
134,Dehesa de Céspedes y Molinos,Carrión de los Céspedes,Sevilla,NaN,NaN
179,Seresuela de Humbrete,Umbrete,Sevilla,NaN,NaN
180,Balzequilla,Aznalcóllar,Sevilla,NaN,NaN
187,Dehesa de las Cruces,Villanueva de las Cruces,Huelva,NaN,NaN
196,Dehesa de Pormedias,Lucena del Puerto,Huelva,NaN,NaN
212,Dehesa de la Iguera,Higuera de la Sierra,Sevilla,NaN,NaN
222,Los Molares,Los Molares,Sevilla,37.160616,-5.708398
226,Boca Dulce,Utrera,Sevilla,NaN,NaN
241,Monte de los Peregrinos,Carmona,Sevilla,NaN,NaN
245,Dehesa de Algarrobo,El Garrobo,Sevilla,NaN,NaN
247,Dehesa de Torre de Palencia,Huelva,Huelva,NaN,NaN
418,Baldios,El Garrobo,Sevilla,NaN,NaN

In [ ]:
# save cleaned dataset
df.to_csv('../data/cleaned/dataset_maderas_clean.csv', index=False)

In [ ]:
# check files in cleaned folder
import os
os.listdir('../data/cleaned')

['dataset_maderas_clean.csv']

In [ ]:
# BASIC DATASET OVERVIEW

In [ ]:
# number of rows and columns
df.shape

(419, 20)

In [ ]:
# column names
df.columns.tolist()

['felling_period',
 'felling_toponymy_source',
 'felling_toponymy_MTN25',
 'felling_latitude_WGS84',
 'felling_longitude_WGS84',
 'municipality',
 'province',
 'landowner_type',
 'landowner_name',
 'tree_species',
 'tree_quantity',
 'tree_quantity_clean',
 'latitude_clean',
 'longitude_clean',
 'province_clean',
 'municipality_clean',
 'landowner_type_clean',
 'landowner_name_clean',
 'tree_species_clean',
 'felling_toponymy_MTN25_clean']

In [ ]:
# general information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 419 entries, 0 to 418
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   felling_period                419 non-null    str
 1   felling_toponymy_source       419 non-null    str
 2   felling_toponymy_MTN25        397 non-null    str
 3   felling_latitude_WGS84        221 non-null    str
 4   felling_longitude_WGS84       221 non-null    str
 5   municipality                  419 non-null    str
 6   province                      419 non-null    str
 7   landowner_type                399 non-null    str
 8   landowner_name                394 non-null    str
 9   tree_species                  401 non-null    str
 10  tree_quantity                 404 non-null    str
 11  tree_quantity_clean           404 non-null    float64
 12  latitude_clean                221 non-null    float64
 13  longitude_clean               221 non-null    float64
 14  province_clean                419 non-null    str
 15  municipality_clean            419 non-null    string
 16  landowner_type_clean          399 non-null    string
 17  landowner_name_clean          394 non-null    string
 18  tree_species_clean            401 non-null    string
 19  felling_toponymy_MTN25_clean  397 non-null    string
dtypes: float64(3), str(12), string(5)
memory usage: 132.5 KB

In [ ]:
# first rows of the cleaned dataset
df.head()

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean,felling_toponymy_MTN25_clean
0,1748-1749,Benahú,Dehesa de Benahú,"36,57689304","-5,509202381",Jeréz de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,622,622.0,36.576893,-5.509202,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak,Dehesa de Benahú
1,1748-1749,Jarda,Dehesa de la Jarda,"36,60223799","-5,6019132409",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,230,230.0,36.602238,-5.601913,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak,Dehesa de la Jarda
2,1748-1749,Barranco de la Fantasma,La Fantasma,"36,6099778174","-5,4648038479",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,240,240.0,36.609978,-5.464804,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak,La Fantasma
3,1748-1749,La Jardilla,La Jardilla,"36,62178904","-5,518366056",Jeréz de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,1457,1457.0,36.621789,-5.518366,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak,La Jardilla
4,1748-1749,Garganta de Millán,Millán,"36,61617144","-5,474945207",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,250,250.0,36.616171,-5.474945,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak,Millán

In [ ]:
# first rows of the cleaned dataset
df.head()

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean,felling_toponymy_MTN25_clean
0,1748-1749,Benahú,Dehesa de Benahú,"36,57689304","-5,509202381",Jeréz de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,622,622.0,36.576893,-5.509202,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak,Dehesa de Benahú
1,1748-1749,Jarda,Dehesa de la Jarda,"36,60223799","-5,6019132409",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,230,230.0,36.602238,-5.601913,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak,Dehesa de la Jarda
2,1748-1749,Barranco de la Fantasma,La Fantasma,"36,6099778174","-5,4648038479",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,240,240.0,36.609978,-5.464804,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak,La Fantasma
3,1748-1749,La Jardilla,La Jardilla,"36,62178904","-5,518366056",Jeréz de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,1457,1457.0,36.621789,-5.518366,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak,La Jardilla
4,1748-1749,Garganta de Millán,Millán,"36,61617144","-5,474945207",Jeréz de la Frontera,Cádiz,NaN,NaN,gall oak,250,250.0,36.616171,-5.474945,Cádiz,Jerez de la Frontera,<NA>,<NA>,gall oak,Millán

In [ ]:
# summary statistics for numeric columns
df.describe()

       tree_quantity_clean  latitude_clean  longitude_clean
count           404.000000      221.000000       221.000000
mean            164.066832       37.163315        -6.056554
std             445.593276        0.395019         0.457356
min               1.000000       36.307821        -7.174165
25%               5.000000       36.799369        -6.364159
50%              25.000000       37.311271        -6.212936
75%             120.750000       37.357908        -5.571195
max            4198.000000       37.952916        -5.107282

In [ ]:
# total number of trees
df['tree_quantity'].sum()

'62223024014572503833843833603703703703703702131406298613003205332044198898 trees1 645 trees3150 trees91 trees2455603 593 trees1818102 trees266 trees2 087 trees186 trees57 trees134 trees12012011956056044844844844844830 trees1113 trees233 trees220 trees582 trees282 trees287286286287338 trees167 trees1113 trees57 trees2120 trees2847 trees234 trees238 trees40  trees40  trees50  trees310  trees11  trees25  trees130  trees80 trees36 trees200 trees40  trees170 trees360 trees18  trees123  trees40  trees60  trees250  trees400  trees231 trees73  trees170  trees160  trees210  trees50  trees74  trees150  trees12  trees7  trees523174930741372984  trees559  trees1137211113112116066192197695595211313468188132953502560101932614217512275941798223145664721264652288871081043001035993002314772519102829341  trees66  trees431318183361461640130301366420185910914271246111112813111121165478220411654034116171617173676630632339517012144010178071411209372527122820204015214221291269112042081188345237 trees232194319112442612722011313212244974108611125211144422631425184723416222222223222129414411113328299668855100  trees103 trees120474605537144635683149421851252540100120471922105421730395514281789612264810959'

In [ ]:
# number of unique municipalities
df['municipality_clean'].nunique()

67

In [ ]:
# number of unique owners
df['owner_clean'].nunique()

KeyError: 'owner_clean'

In [ ]:
# total number of trees
df['tree_quantity_clean'].sum()

np.float64(66283.0)

In [ ]:
# number of unique landowners
df['landowner_name_clean'].nunique()

245

In [ ]:
# number of unique species
df['tree_species_clean'].nunique()

9

In [ ]:
# number of unique provinces
df['province_clean'].nunique()

4

In [ ]:
# save the updated cleaned dataset
df.to_csv('../data/cleaned/dataset_maderas_clean.csv', index=False)

In [ ]:
list(df.columns)

['felling_period',
 'felling_toponymy_source',
 'felling_toponymy_MTN25',
 'felling_latitude_WGS84',
 'felling_longitude_WGS84',
 'municipality',
 'province',
 'landowner_type',
 'landowner_name',
 'tree_species',
 'tree_quantity',
 'tree_quantity_clean',
 'latitude_clean',
 'longitude_clean',
 'province_clean',
 'municipality_clean',
 'landowner_type_clean',
 'landowner_name_clean',
 'tree_species_clean']

In [ ]:
df_final = df[[
    'felling_period',
    'felling_toponymy_source',
    'felling_toponymy_MTN25',
    'latitude_clean',
    'longitude_clean',
    'municipality_clean',
    'province_clean',
    'landowner_type_clean',
    'landowner_name_clean',
    'tree_species_clean',
    'tree_quantity_clean'
]]

In [ ]:
df_final = df_final.rename(columns={
    'latitude_clean': 'latitude',
    'longitude_clean': 'longitude',
    'municipality_clean': 'municipality',
    'province_clean': 'province',
    'landowner_type_clean': 'landownership',
    'landowner_name_clean': 'landowner_name',
    'tree_species_clean': 'tree_species',
    'tree_quantity_clean': 'tree_quantity'
})

In [ ]:
df_final.head()

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,latitude,longitude,municipality,province,landownership,landowner_name,tree_species,tree_quantity
0,1748-1749,Benahú,Dehesa de Benahú,36.576893,-5.509202,Jerez de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,622.0
1,1748-1749,Jarda,Dehesa de la Jarda,36.602238,-5.601913,Jerez de la Frontera,Cádiz,<NA>,<NA>,gall oak,230.0
2,1748-1749,Barranco de la Fantasma,La Fantasma,36.609978,-5.464804,Jerez de la Frontera,Cádiz,<NA>,<NA>,gall oak,240.0
3,1748-1749,La Jardilla,La Jardilla,36.621789,-5.518366,Jerez de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,1457.0
4,1748-1749,Garganta de Millán,Millán,36.616171,-5.474945,Jerez de la Frontera,Cádiz,<NA>,<NA>,gall oak,250.0

In [ ]:
df_final.to_csv('../data/cleaned/dataset_maderas_final.csv', index=False)

In [ ]:
list(df_final.columns)

['felling_period',
 'felling_toponymy_source',
 'felling_toponymy_MTN25',
 'latitude',
 'longitude',
 'municipality',
 'province',
 'landownership',
 'landowner_name',
 'tree_species',
 'tree_quantity']

In [ ]:
df['province_clean'] = df['province_clean'].fillna('undefined')
df['municipality_clean'] = df['municipality_clean'].fillna('undefined')
df['landowner_type_clean'] = df['landowner_type_clean'].fillna('undefined')
df['landowner_name_clean'] = df['landowner_name_clean'].fillna('undefined')
df['tree_species_clean'] = df['tree_species_clean'].fillna('undefined')

In [ ]:


df['latitude_clean'] = df['latitude_clean'].fillna(0)
df['longitude_clean'] = df['longitude_clean'].fillna(0)

In [ ]:
df['tree_quantity_clean'] = df['tree_quantity_clean'].fillna(0)

In [ ]:
df.isna().sum()

felling_period               0
felling_toponymy_source      0
felling_toponymy_MTN25      22
felling_latitude_WGS84     198
felling_longitude_WGS84    198
municipality                 0
province                     0
landowner_type              20
landowner_name               0
tree_species                18
tree_quantity               15
tree_quantity_clean          0
latitude_clean               0
longitude_clean              0
province_clean               0
municipality_clean           0
landowner_type_clean         0
landowner_name_clean         0
tree_species_clean           0
dtype: int64

In [ ]:
df[
    [
        'province_clean',
        'municipality_clean',
        'landowner_type_clean',
        'landowner_name_clean',
        'tree_species_clean',
        'tree_quantity_clean',
        'latitude_clean',
        'longitude_clean'
    ]
].sample(10)

,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean,tree_quantity_clean,latitude_clean,longitude_clean
48,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak,560.0,36.544107,-5.517248
150,Sevilla,Huévar,noble estate,Marqués de La Fuente,holm oak,25.0,37.341307,-6.341365
413,Sevilla,El Castillo de las Guardas,comunal,El Castillo de las Guardas,holm oak,96.0,37.670209,-6.215808
410,Sevilla,Umbrete,ecclesiastic,Cardenal Infante Luis Antonio Jaime de Borbón ...,holm oak,28.0,37.284579,-6.195807
223,Sevilla,Utrera,ecclesiastic,Convento de La Concepción,pine,1.0,37.182886,-5.801093
159,Sevilla,Carmona,noble estate,Marqués de Saltillo,pine,7.0,37.526614,-5.760962
69,Cádiz,Jimena de la Frontera,noble estate,Duque de Medina Sidonia,gall oak,2847.0,36.418022,-5.571195
8,Cádiz,Grazalema,undefined,undefined,undefined species,360.0,36.748004,-5.426724
286,Huelva,Hinojos,ecclesiastic,Hermandad del Santíssimo Sacramento,pine,22.0,0.000000,0.000000
114,Huelva,Hinojos,private,"José Campo, Pedro de los Reyes",pine,30.0,0.000000,0.000000

In [ ]:
df_final = df[
    [
        'felling_period',
        'felling_toponymy_source',
        'felling_toponymy_MTN25',
        'latitude_clean',
        'longitude_clean',
        'municipality_clean',
        'province_clean',
        'landowner_type_clean',
        'landowner_name_clean',
        'tree_species_clean',
        'tree_quantity_clean'
    ]
].copy()

In [ ]:
df_final.columns = [
    'felling_period',
    'felling_toponymy_source',
    'felling_toponymy_MTN25',
    'latitude',
    'longitude',
    'municipality',
    'province',
    'landownership',
    'landowner_name',
    'tree_species',
    'tree_quantity'
]

In [ ]:
df_final.head()

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,latitude,longitude,municipality,province,landownership,landowner_name,tree_species,tree_quantity
0,1748-1749,Benahú,Dehesa de Benahú,36.576893,-5.509202,Jerez de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,622.0
1,1748-1749,Jarda,Dehesa de la Jarda,36.602238,-5.601913,Jerez de la Frontera,Cádiz,undefined,undefined,gall oak,230.0
2,1748-1749,Barranco de la Fantasma,La Fantasma,36.609978,-5.464804,Jerez de la Frontera,Cádiz,undefined,undefined,gall oak,240.0
3,1748-1749,La Jardilla,La Jardilla,36.621789,-5.518366,Jerez de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,1457.0
4,1748-1749,Garganta de Millán,Millán,36.616171,-5.474945,Jerez de la Frontera,Cádiz,undefined,undefined,gall oak,250.0

In [ ]:
df_final.to_csv('../data/cleaned/dataset_maderas_final.csv', index=False)

In [ ]:
df_final.shape

(419, 11)

In [ ]:
df_final.head()

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,latitude,longitude,municipality,province,landownership,landowner_name,tree_species,tree_quantity
0,1748-1749,Benahú,Dehesa de Benahú,36.576893,-5.509202,Jerez de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,622.0
1,1748-1749,Jarda,Dehesa de la Jarda,36.602238,-5.601913,Jerez de la Frontera,Cádiz,undefined,undefined,gall oak,230.0
2,1748-1749,Barranco de la Fantasma,La Fantasma,36.609978,-5.464804,Jerez de la Frontera,Cádiz,undefined,undefined,gall oak,240.0
3,1748-1749,La Jardilla,La Jardilla,36.621789,-5.518366,Jerez de la Frontera,Cádiz,comunal,Jerez de la Frontera,gall oak,1457.0
4,1748-1749,Garganta de Millán,Millán,36.616171,-5.474945,Jerez de la Frontera,Cádiz,undefined,undefined,gall oak,250.0

In [ ]:
df.isna().sum()

felling_period               0
felling_toponymy_source      0
felling_toponymy_MTN25      22
felling_latitude_WGS84     198
felling_longitude_WGS84    198
municipality                 0
province                     0
landowner_type              20
landowner_name               0
tree_species                18
tree_quantity               15
tree_quantity_clean          0
latitude_clean               0
longitude_clean              0
province_clean               0
municipality_clean           0
landowner_type_clean         0
landowner_name_clean         0
tree_species_clean           0
dtype: int64

In [ ]:
df.loc[22]

felling_period                        1748-1750
felling_toponymy_source               El Palero
felling_toponymy_MTN25              Los Molares
felling_latitude_WGS84              36,63041184
felling_longitude_WGS84            -5,488708528
municipality               Jeréz de la Frontera
province                                  Cádiz
landowner_type                              NaN
landowner_name              undefined landowner
tree_species                                NaN
tree_quantity                               NaN
tree_quantity_clean                         0.0
latitude_clean                        36.630412
longitude_clean                       -5.488709
province_clean                            Cádiz
municipality_clean         Jerez de la Frontera
landowner_type_clean                  undefined
landowner_name_clean                  undefined
tree_species_clean            undefined species
Name: 22, dtype: object

In [ ]:
df.loc[22, 'felling_toponymy_MTN25'] = 'Arroyo del Palerillo Bajo'

In [ ]:
df.loc[222, 'felling_toponymy_MTN25'] = 'Los Molares'

In [ ]:
df[df['felling_toponymy_MTN25'].isna()]

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean
25,1748-1751,Castellar,NaN,NaN,NaN,Castellar de la Frontera,Cádiz,comunal,Castellar de la Frontera,oak,898 trees,898.0,0.0,0.0,Cádiz,Castellar de la Frontera,comunal,Castellar de la Frontera,oak
26,1748-1751,Dehesa de Alcalá del Valle,NaN,NaN,NaN,Alcalá del Valle,Cádiz,comunal,Alcalá del Valle,oak,1 645 trees,1645.0,0.0,0.0,Cádiz,Alcalá del Valle,comunal,Alcalá del Valle,oak
68,1750,Baldíos de Jimena,NaN,NaN,NaN,Jimena de la Frontera,Cádiz,fallow land,Jimena de la Frontera,oak,2120 trees,2120.0,0.0,0.0,Cádiz,Jimena de la Frontera,fallow land,Jimena de la Frontera,oak
74,1750,Tronco,NaN,NaN,NaN,Jimena de la Frontera,Cádiz,comunal,Jimena de la Frontera,"oak, gall oak",NaN,0.0,0.0,0.0,Cádiz,Jimena de la Frontera,comunal,Jimena de la Frontera,"oak, gall oak"
75,1750,Moros,NaN,NaN,NaN,Jimena de la Frontera,Cádiz,comunal,Jimena de la Frontera,"oak, gall oak",NaN,0.0,0.0,0.0,Cádiz,Jimena de la Frontera,comunal,Jimena de la Frontera,"oak, gall oak"
76,1750,Lajuela,NaN,NaN,NaN,Jimena de la Frontera,Cádiz,comunal,Jimena de la Frontera,"oak, gall oak",NaN,0.0,0.0,0.0,Cádiz,Jimena de la Frontera,comunal,Jimena de la Frontera,"oak, gall oak"
77,1750,Monte de la Zarza,NaN,NaN,NaN,Jimena de la Frontera,Cádiz,comunal,Jimena de la Frontera,"oak, gall oak",NaN,0.0,0.0,0.0,Cádiz,Jimena de la Frontera,comunal,Jimena de la Frontera,"oak, gall oak"
78,1750-1751,Sierra de Jerez,NaN,NaN,NaN,Jeréz de la Frontera,Cádiz,NaN,undefined landowner,NaN,238 trees,238.0,0.0,0.0,Cádiz,Jerez de la Frontera,undefined,undefined,undefined species
95,1748-1749,Dehesa de Molino de los Zéspedes,NaN,NaN,NaN,Carrión de los Céspedes,Sevilla,noble estate,Marqués de Villafranca,holm oak,60 trees,60.0,0.0,0.0,Sevilla,Carrión de los Céspedes,noble estate,Marqués de Villa Franca,holm oak
116,1748-1749,Dehesa de Torre de Palencia,NaN,NaN,NaN,Huelva,Huelva,private,Diego de Guzman,holm oak,NaN,0.0,0.0,0.0,Huelva,Huelva,private,Diego de Guzmán,holm oak
134,1748-1750,Dehesa de Céspedes y Molinos,NaN,NaN,NaN,Carrión de los Céspedes,Sevilla,noble estate,Marqués de Villafranca,holm oak,66,66.0,0.0,0.0,Sevilla,Carrión de los Céspedes,noble estate,Marqués de Villa Franca,holm oak
179,1749,Seresuela de Humbrete,NaN,NaN,NaN,Umbrete,Sevilla,ecclesiastic,Cardenal Infante Luis Antonio Jaime de Borbón ...,holm oak,22,22.0,0.0,0.0,Sevilla,Umbrete,ecclesiastic,Cardenal Infante Luis Antonio Jaime de Borbón ...,holm oak
180,1749,Balzequilla,NaN,NaN,NaN,Aznalcóllar,Sevilla,comunal,Aznalcóllar,holm oak,88,88.0,0.0,0.0,Sevilla,Aznalcóllar,comunal,Aznalcóllar,holm oak
187,1749-1750,Dehesa de las Cruces,NaN,NaN,NaN,Villanueva de las Cruces,Huelva,comunal,Villanueva de las Cruces,holm oak,300,300.0,0.0,0.0,Huelva,Villanueva de las Cruces,comunal,Villanueva de las Cruces,holm oak
196,1749-1750,Dehesa de Pormedias,NaN,NaN,NaN,Lucena del Puerto,Huelva,"comunal, ecclesiastic","Lucena del Puerto, Convento de la Luz de Lucen...",holm oak,29,29.0,0.0,0.0,Huelva,Lucena del Puerto,"comunal, ecclesiastic","Lucena del Puerto, Convento de la Luz de Lucen...",holm oak
212,1749-1750,Dehesa de la Iguera,NaN,NaN,NaN,Higuera de la Sierra,Sevilla,comunal,Higuera de la Sierra,holm oak,64,64.0,0.0,0.0,Sevilla,Higuera de la Sierra,comunal,Higuera de la Sierra,holm oak
226,1749-1750,Boca Dulce,NaN,NaN,NaN,Utrera,Sevilla,private,Lorenzo de Lana,pine,1,1.0,0.0,0.0,Sevilla,Utrera,private,Lorenzo de Lana,pine
241,1749-1750,Monte de los Peregrinos,NaN,NaN,NaN,Carmona,Sevilla,noble estate,Marqués de Saltillo,pine,78,78.0,0.0,0.0,Sevilla,Carmona,noble estate,Marqués de Saltillo,pine
245,1749-1750,Dehesa de Algarrobo,NaN,NaN,NaN,El Garrobo,Sevilla,comunal,El Garrobo,holm oak,40,40.0,0.0,0.0,Sevilla,El Garrobo,comunal,El Garrobo,holm oak
247,1749-1750,Dehesa de Torre de Palencia,NaN,NaN,NaN,Huelva,Huelva,NaN,undefined landowner,holm oak,41,41.0,0.0,0.0,Huelva,Huelva,undefined,undefined,holm oak
418,1751,Baldios,NaN,NaN,NaN,El Garrobo,Sevilla,comunal,El Garrobo,holm oak,59,59.0,0.0,0.0,Sevilla,El Garrobo,comunal,El Garrobo,holm oak

In [ ]:
df[df['felling_latitude_WGS84'].isna()]

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean
20,1748-1749,Santa María de Guadalupe,El Bosque,NaN,NaN,El Bosque,Cádiz,noble estate,Duque de Arcos,gall oak,204,204.0,0.0,0.0,Cádiz,El Bosque,noble estate,Duque de Arcos,gall oak
24,1748-1750,Ronda,Ronda,NaN,NaN,Ronda,Malaga,comunal,ronda,gall oak,4198,4198.0,0.0,0.0,Málaga,Ronda,comunal,Ronda,gall oak
25,1748-1751,Castellar,NaN,NaN,NaN,Castellar de la Frontera,Cádiz,comunal,Castellar de la Frontera,oak,898 trees,898.0,0.0,0.0,Cádiz,Castellar de la Frontera,comunal,Castellar de la Frontera,oak
26,1748-1751,Dehesa de Alcalá del Valle,NaN,NaN,NaN,Alcalá del Valle,Cádiz,comunal,Alcalá del Valle,oak,1 645 trees,1645.0,0.0,0.0,Cádiz,Alcalá del Valle,comunal,Alcalá del Valle,oak
27,1748-1751,Santa María de Guadalupe / El Bosque,El Bosque,NaN,NaN,El Bosque,Cádiz,noble estate,Duque de Arcos,oak,NaN,0.0,0.0,0.0,Cádiz,El Bosque,noble estate,Duque de Arcos,oak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,1751,Cala,Cala,NaN,NaN,Cala,Huelva,comunal,cabildo de la villa de Cala,holm oak,494,494.0,0.0,0.0,Huelva,Cala,comunal,cabildo de la villa de Cala,holm oak
392,1751,Cala,Cala,NaN,NaN,Cala,Huelva,private,"Antonio Perez, Maria Dominguez",holm oak,21,21.0,0.0,0.0,Huelva,Cala,private,"Antonio Perez, María Domínguez",holm oak
393,1751,Santa Olalla del Cala,Santa Olalla del Cala,NaN,NaN,Santa Olalla del Cala,Huelva,comunal,Santa Olalla del Cala,holm oak,851,851.0,0.0,0.0,Huelva,Santa Olalla del Cala,comunal,Santa Olalla del Cala,holm oak
417,1751,Patronato,Patronato,NaN,NaN,El Castillo de las Guardas,Sevilla,ecclesiastic,Vigario de El Castillo de las Guardas,holm oak,109,109.0,0.0,0.0,Sevilla,El Castillo de las Guardas,ecclesiastic,Vigario de El Castillo de las Guardas,holm oak
418,1751,Baldios,NaN,NaN,NaN,El Garrobo,Sevilla,comunal,El Garrobo,holm oak,59,59.0,0.0,0.0,Sevilla,El Garrobo,comunal,El Garrobo,holm oak

In [ ]:
df[df['landowner_type'].isna()]

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean
1,1748-1749,Jarda,Dehesa de la Jarda,"36,60223799","-5,6019132409",Jeréz de la Frontera,Cádiz,NaN,undefined landowner,gall oak,230,230.0,36.602238,-5.601913,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak
2,1748-1749,Barranco de la Fantasma,La Fantasma,"36,6099778174","-5,4648038479",Jeréz de la Frontera,Cádiz,NaN,undefined landowner,gall oak,240,240.0,36.609978,-5.464804,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak
4,1748-1749,Garganta de Millán,Millán,"36,61617144","-5,474945207",Jeréz de la Frontera,Cádiz,NaN,undefined landowner,gall oak,250,250.0,36.616171,-5.474945,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak
5,1748-1749,Campo de las Encinas,Campo de las Encinas,"36,75292427","-5,438416824",Grazalema,Cádiz,NaN,undefined landowner,NaN,383,383.0,36.752924,-5.438417,Cádiz,Grazalema,undefined,undefined,undefined species
6,1748-1749,Breña del Água,Breña del Água,"36,79982924","-5,457767886",Grazalema,Cádiz,NaN,undefined landowner,NaN,384,384.0,36.799829,-5.457768,Cádiz,Grazalema,undefined,undefined,undefined species
7,1748-1749,Huertas de Benahoma,Benahoma,"36,76518276","-5,463346881",Grazalema,Cádiz,NaN,undefined landowner,NaN,383,383.0,36.765183,-5.463347,Cádiz,Grazalema,undefined,undefined,undefined species
8,1748-1749,Monte del Boyar,El Boyal,"36,74800409","-5,426723999",Grazalema,Cádiz,NaN,undefined landowner,NaN,360,360.0,36.748004,-5.426724,Cádiz,Grazalema,undefined,undefined,undefined species
9,1748-1749,Chorreadero,Chorreadero,"36,83427701","-5,5176234176",Zahara de la sierra,Cádiz,NaN,undefined landowner,NaN,370,370.0,36.834277,-5.517623,Cádiz,Zahara de la Sierra,undefined,undefined,undefined species
11,1748-1750,El Canchal,El Canchal,"36,84293228","-5,520069592",algodonales,Cádiz,NaN,undefined landowner,NaN,370,370.0,36.842932,-5.520070,Cádiz,Algodonales,undefined,undefined,undefined species
12,1748-1749,Chorreadero,Chorreadero,"36,8340336855","-5,529137619",prado del rey,Cádiz,NaN,undefined landowner,NaN,370,370.0,36.834034,-5.529138,Cádiz,Prado del Rey,undefined,undefined,undefined species
13,1748-1749,El Canchal,El Canchal,"36,8202832219","-5,5273083452\n",prado del rey,Cádiz,NaN,undefined landowner,NaN,370,370.0,36.820283,-5.527308,Cádiz,Prado del Rey,undefined,undefined,undefined species
14,1748-1749,Vegas de Juan Peon,Las Vegas,"36,79936876","-5,518731601",prado del rey,Cádiz,NaN,undefined landowner,NaN,213,213.0,36.799369,-5.518732,Cádiz,Prado del Rey,undefined,undefined,undefined species
15,1748-1749,Moracha Alta,La Moracha,"36,50804025","-5,576951442","Alcalá de los Gazules,",Cádiz,NaN,undefined landowner,"gall oak, cork oak",1406,1406.0,36.508040,-5.576951,Cádiz,Alcalá de los Gazules,undefined,undefined,"gall oak, cork oak"
17,1748-1749,Bañuelos,Roza de Bañuelos,"36,58488386","-5,444877644",Cortes de la frontera,Málaga,NaN,undefined landowner,NaN,1300,1300.0,36.584884,-5.444878,Málaga,Cortes de la Frontera,undefined,undefined,undefined species
18,1748-1749,Monte del Berrueco,El Berrueco,"36,61847484","-5,417707898",Cortes de la frontera,Málaga,NaN,undefined landowner,NaN,320,320.0,36.618475,-5.417708,Málaga,Cortes de la Frontera,undefined,undefined,undefined species
19,1748-1749,Puerto de las Encinas,Puerto de la Encina,"36,59685737","-5,440138557",Cortes de la frontera,Málaga,NaN,undefined landowner,NaN,533,533.0,36.596857,-5.440139,Málaga,Cortes de la Frontera,undefined,undefined,undefined species
21,1748-1750,El Enimigo,Cerro del Enimigo,"36,60071713","-5,47458295",Jeréz de la Frontera,Cádiz,NaN,undefined landowner,NaN,NaN,0.0,36.600717,-5.474583,Cádiz,Jerez de la Frontera,undefined,undefined,undefined species
22,1748-1750,El Palero,Arroyo del Palerillo Bajo,"36,63041184","-5,488708528",Jeréz de la Frontera,Cádiz,NaN,undefined landowner,NaN,NaN,0.0,36.630412,-5.488709,Cádiz,Jerez de la Frontera,undefined,undefined,undefined species
78,1750-1751,Sierra de Jerez,NaN,NaN,NaN,Jeréz de la Frontera,Cádiz,NaN,undefined landowner,NaN,238 trees,238.0,0.000000,0.000000,Cádiz,Jerez de la Frontera,undefined,undefined,undefined species
247,1749-1750,Dehesa de Torre de Palencia,NaN,NaN,NaN,Huelva,Huelva,NaN,undefined landowner,holm oak,41,41.0,0.000000,0.000000,Huelva,Huelva,undefined,undefined,holm oak

In [ ]:
df[df['tree_species'].isna()]

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean
5,1748-1749,Campo de las Encinas,Campo de las Encinas,"36,75292427","-5,438416824",Grazalema,Cádiz,NaN,undefined landowner,NaN,383,383.0,36.752924,-5.438417,Cádiz,Grazalema,undefined,undefined,undefined species
6,1748-1749,Breña del Água,Breña del Água,"36,79982924","-5,457767886",Grazalema,Cádiz,NaN,undefined landowner,NaN,384,384.0,36.799829,-5.457768,Cádiz,Grazalema,undefined,undefined,undefined species
7,1748-1749,Huertas de Benahoma,Benahoma,"36,76518276","-5,463346881",Grazalema,Cádiz,NaN,undefined landowner,NaN,383,383.0,36.765183,-5.463347,Cádiz,Grazalema,undefined,undefined,undefined species
8,1748-1749,Monte del Boyar,El Boyal,"36,74800409","-5,426723999",Grazalema,Cádiz,NaN,undefined landowner,NaN,360,360.0,36.748004,-5.426724,Cádiz,Grazalema,undefined,undefined,undefined species
9,1748-1749,Chorreadero,Chorreadero,"36,83427701","-5,5176234176",Zahara de la sierra,Cádiz,NaN,undefined landowner,NaN,370,370.0,36.834277,-5.517623,Cádiz,Zahara de la Sierra,undefined,undefined,undefined species
10,1748-1749,El Canchal,El Canchal,"36,83170657","-5,5044698646",Zahara de la sierra,Cádiz,noble estate,Duque de Arcos,NaN,370,370.0,36.831707,-5.504470,Cádiz,Zahara de la Sierra,noble estate,Duque de Arcos,undefined species
11,1748-1750,El Canchal,El Canchal,"36,84293228","-5,520069592",algodonales,Cádiz,NaN,undefined landowner,NaN,370,370.0,36.842932,-5.520070,Cádiz,Algodonales,undefined,undefined,undefined species
12,1748-1749,Chorreadero,Chorreadero,"36,8340336855","-5,529137619",prado del rey,Cádiz,NaN,undefined landowner,NaN,370,370.0,36.834034,-5.529138,Cádiz,Prado del Rey,undefined,undefined,undefined species
13,1748-1749,El Canchal,El Canchal,"36,8202832219","-5,5273083452\n",prado del rey,Cádiz,NaN,undefined landowner,NaN,370,370.0,36.820283,-5.527308,Cádiz,Prado del Rey,undefined,undefined,undefined species
14,1748-1749,Vegas de Juan Peon,Las Vegas,"36,79936876","-5,518731601",prado del rey,Cádiz,NaN,undefined landowner,NaN,213,213.0,36.799369,-5.518732,Cádiz,Prado del Rey,undefined,undefined,undefined species
17,1748-1749,Bañuelos,Roza de Bañuelos,"36,58488386","-5,444877644",Cortes de la frontera,Málaga,NaN,undefined landowner,NaN,1300,1300.0,36.584884,-5.444878,Málaga,Cortes de la Frontera,undefined,undefined,undefined species
18,1748-1749,Monte del Berrueco,El Berrueco,"36,61847484","-5,417707898",Cortes de la frontera,Málaga,NaN,undefined landowner,NaN,320,320.0,36.618475,-5.417708,Málaga,Cortes de la Frontera,undefined,undefined,undefined species
19,1748-1749,Puerto de las Encinas,Puerto de la Encina,"36,59685737","-5,440138557",Cortes de la frontera,Málaga,NaN,undefined landowner,NaN,533,533.0,36.596857,-5.440139,Málaga,Cortes de la Frontera,undefined,undefined,undefined species
21,1748-1750,El Enimigo,Cerro del Enimigo,"36,60071713","-5,47458295",Jeréz de la Frontera,Cádiz,NaN,undefined landowner,NaN,NaN,0.0,36.600717,-5.474583,Cádiz,Jerez de la Frontera,undefined,undefined,undefined species
22,1748-1750,El Palero,Arroyo del Palerillo Bajo,"36,63041184","-5,488708528",Jeréz de la Frontera,Cádiz,NaN,undefined landowner,NaN,NaN,0.0,36.630412,-5.488709,Cádiz,Jerez de la Frontera,undefined,undefined,undefined species
29,1748-1751,Ronda,Ronda,NaN,NaN,Ronda,Malaga,comunal,ronda,NaN,91 trees,91.0,0.000000,0.000000,Málaga,Ronda,comunal,Ronda,undefined species
30,1749,Sauceda,La Sauceda,"36,52543016","-5,583841408",Cortes de la frontera,Málaga,private,Pedro Manuel Motezuma,NaN,NaN,0.0,36.525430,-5.583841,Málaga,Cortes de la Frontera,private,Pedro Manuel Motezuma,undefined species
78,1750-1751,Sierra de Jerez,NaN,NaN,NaN,Jeréz de la Frontera,Cádiz,NaN,undefined landowner,NaN,238 trees,238.0,0.000000,0.000000,Cádiz,Jerez de la Frontera,undefined,undefined,undefined species

In [ ]:
df.isna().sum()

felling_period               0
felling_toponymy_source      0
felling_toponymy_MTN25      21
felling_latitude_WGS84     198
felling_longitude_WGS84    198
municipality                 0
province                     0
landowner_type              20
landowner_name               0
tree_species                18
tree_quantity               15
tree_quantity_clean          0
latitude_clean               0
longitude_clean              0
province_clean               0
municipality_clean           0
landowner_type_clean         0
landowner_name_clean         0
tree_species_clean           0
dtype: int64

In [ ]:
df['felling_toponymy_MTN25'] = df['felling_toponymy_MTN25'].fillna('undefined')

In [ ]:
df['felling_toponymy_MTN25'].value_counts(dropna=False)

felling_toponymy_MTN25
Utrera              53
Almonte             30
Hinojos             22
undefined           21
Aznalcázar           8
                    ..
Dehesa de Puyana     1
Casa Sierra          1
El Badío             1
El Cañuelo           1
Patronato            1
Name: count, Length: 195, dtype: int64

In [ ]:
df[df['felling_toponymy_MTN25'] == 'undefined']

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,felling_latitude_WGS84,felling_longitude_WGS84,municipality,province,landowner_type,landowner_name,tree_species,tree_quantity,tree_quantity_clean,latitude_clean,longitude_clean,province_clean,municipality_clean,landowner_type_clean,landowner_name_clean,tree_species_clean
25,1748-1751,Castellar,undefined,NaN,NaN,Castellar de la Frontera,Cádiz,comunal,Castellar de la Frontera,oak,898 trees,898.0,0.0,0.0,Cádiz,Castellar de la Frontera,comunal,Castellar de la Frontera,oak
26,1748-1751,Dehesa de Alcalá del Valle,undefined,NaN,NaN,Alcalá del Valle,Cádiz,comunal,Alcalá del Valle,oak,1 645 trees,1645.0,0.0,0.0,Cádiz,Alcalá del Valle,comunal,Alcalá del Valle,oak
68,1750,Baldíos de Jimena,undefined,NaN,NaN,Jimena de la Frontera,Cádiz,fallow land,Jimena de la Frontera,oak,2120 trees,2120.0,0.0,0.0,Cádiz,Jimena de la Frontera,fallow land,Jimena de la Frontera,oak
74,1750,Tronco,undefined,NaN,NaN,Jimena de la Frontera,Cádiz,comunal,Jimena de la Frontera,"oak, gall oak",NaN,0.0,0.0,0.0,Cádiz,Jimena de la Frontera,comunal,Jimena de la Frontera,"oak, gall oak"
75,1750,Moros,undefined,NaN,NaN,Jimena de la Frontera,Cádiz,comunal,Jimena de la Frontera,"oak, gall oak",NaN,0.0,0.0,0.0,Cádiz,Jimena de la Frontera,comunal,Jimena de la Frontera,"oak, gall oak"
76,1750,Lajuela,undefined,NaN,NaN,Jimena de la Frontera,Cádiz,comunal,Jimena de la Frontera,"oak, gall oak",NaN,0.0,0.0,0.0,Cádiz,Jimena de la Frontera,comunal,Jimena de la Frontera,"oak, gall oak"
77,1750,Monte de la Zarza,undefined,NaN,NaN,Jimena de la Frontera,Cádiz,comunal,Jimena de la Frontera,"oak, gall oak",NaN,0.0,0.0,0.0,Cádiz,Jimena de la Frontera,comunal,Jimena de la Frontera,"oak, gall oak"
78,1750-1751,Sierra de Jerez,undefined,NaN,NaN,Jeréz de la Frontera,Cádiz,NaN,undefined landowner,NaN,238 trees,238.0,0.0,0.0,Cádiz,Jerez de la Frontera,undefined,undefined,undefined species
95,1748-1749,Dehesa de Molino de los Zéspedes,undefined,NaN,NaN,Carrión de los Céspedes,Sevilla,noble estate,Marqués de Villafranca,holm oak,60 trees,60.0,0.0,0.0,Sevilla,Carrión de los Céspedes,noble estate,Marqués de Villa Franca,holm oak
116,1748-1749,Dehesa de Torre de Palencia,undefined,NaN,NaN,Huelva,Huelva,private,Diego de Guzman,holm oak,NaN,0.0,0.0,0.0,Huelva,Huelva,private,Diego de Guzmán,holm oak
134,1748-1750,Dehesa de Céspedes y Molinos,undefined,NaN,NaN,Carrión de los Céspedes,Sevilla,noble estate,Marqués de Villafranca,holm oak,66,66.0,0.0,0.0,Sevilla,Carrión de los Céspedes,noble estate,Marqués de Villa Franca,holm oak
179,1749,Seresuela de Humbrete,undefined,NaN,NaN,Umbrete,Sevilla,ecclesiastic,Cardenal Infante Luis Antonio Jaime de Borbón ...,holm oak,22,22.0,0.0,0.0,Sevilla,Umbrete,ecclesiastic,Cardenal Infante Luis Antonio Jaime de Borbón ...,holm oak
180,1749,Balzequilla,undefined,NaN,NaN,Aznalcóllar,Sevilla,comunal,Aznalcóllar,holm oak,88,88.0,0.0,0.0,Sevilla,Aznalcóllar,comunal,Aznalcóllar,holm oak
187,1749-1750,Dehesa de las Cruces,undefined,NaN,NaN,Villanueva de las Cruces,Huelva,comunal,Villanueva de las Cruces,holm oak,300,300.0,0.0,0.0,Huelva,Villanueva de las Cruces,comunal,Villanueva de las Cruces,holm oak
196,1749-1750,Dehesa de Pormedias,undefined,NaN,NaN,Lucena del Puerto,Huelva,"comunal, ecclesiastic","Lucena del Puerto, Convento de la Luz de Lucen...",holm oak,29,29.0,0.0,0.0,Huelva,Lucena del Puerto,"comunal, ecclesiastic","Lucena del Puerto, Convento de la Luz de Lucen...",holm oak
212,1749-1750,Dehesa de la Iguera,undefined,NaN,NaN,Higuera de la Sierra,Sevilla,comunal,Higuera de la Sierra,holm oak,64,64.0,0.0,0.0,Sevilla,Higuera de la Sierra,comunal,Higuera de la Sierra,holm oak
226,1749-1750,Boca Dulce,undefined,NaN,NaN,Utrera,Sevilla,private,Lorenzo de Lana,pine,1,1.0,0.0,0.0,Sevilla,Utrera,private,Lorenzo de Lana,pine
241,1749-1750,Monte de los Peregrinos,undefined,NaN,NaN,Carmona,Sevilla,noble estate,Marqués de Saltillo,pine,78,78.0,0.0,0.0,Sevilla,Carmona,noble estate,Marqués de Saltillo,pine
245,1749-1750,Dehesa de Algarrobo,undefined,NaN,NaN,El Garrobo,Sevilla,comunal,El Garrobo,holm oak,40,40.0,0.0,0.0,Sevilla,El Garrobo,comunal,El Garrobo,holm oak
247,1749-1750,Dehesa de Torre de Palencia,undefined,NaN,NaN,Huelva,Huelva,NaN,undefined landowner,holm oak,41,41.0,0.0,0.0,Huelva,Huelva,undefined,undefined,holm oak
418,1751,Baldios,undefined,NaN,NaN,El Garrobo,Sevilla,comunal,El Garrobo,holm oak,59,59.0,0.0,0.0,Sevilla,El Garrobo,comunal,El Garrobo,holm oak

In [ ]:
df.isna().sum()

felling_period               0
felling_toponymy_source      0
felling_toponymy_MTN25       0
felling_latitude_WGS84     198
felling_longitude_WGS84    198
municipality                 0
province                     0
landowner_type              20
landowner_name               0
tree_species                18
tree_quantity               15
tree_quantity_clean          0
latitude_clean               0
longitude_clean              0
province_clean               0
municipality_clean           0
landowner_type_clean         0
landowner_name_clean         0
tree_species_clean           0
dtype: int64

In [ ]:
df_final = df[
    [
        'felling_period',
        'felling_toponymy_source',
        'felling_toponymy_MTN25',
        'tree_quantity_clean',
        'latitude_clean',
        'longitude_clean',
        'province_clean',
        'municipality_clean',
        'landowner_type_clean',
        'landowner_name_clean',
        'tree_species_clean'
    ]
].copy()

In [ ]:
df_final.columns = [
    'felling_period',
    'felling_toponymy_source',
    'felling_toponymy_MTN25',
    'tree_quantity',
    'latitude',
    'longitude',
    'province',
    'municipality',
    'landownership',
    'landowner_name',
    'tree_species'
]

In [ ]:
df_final.to_csv('../data/cleaned/dataset_maderas_final.csv', index=False)

In [ ]:
df_final.head()

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,tree_quantity,latitude,longitude,province,municipality,landownership,landowner_name,tree_species
0,1748-1749,Benahú,Dehesa de Benahú,622.0,36.576893,-5.509202,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak
1,1748-1749,Jarda,Dehesa de la Jarda,230.0,36.602238,-5.601913,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak
2,1748-1749,Barranco de la Fantasma,La Fantasma,240.0,36.609978,-5.464804,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak
3,1748-1749,La Jardilla,La Jardilla,1457.0,36.621789,-5.518366,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak
4,1748-1749,Garganta de Millán,Millán,250.0,36.616171,-5.474945,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak

In [ ]:
df_final.sample(100)

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,tree_quantity,latitude,longitude,province,municipality,landownership,landowner_name,tree_species
394,1751,Cañada,Cañada de los Charcos,25.0,37.935284,-6.231529,Huelva,Santa Olalla del Cala,private,undefined,holm oak
276,1749-1751,Hinojos,Hinojos,25.0,0.000000,0.000000,Huelva,Hinojos,private,Simón Naranjo,pine
167,1749,Pozo del Zierbo,Pozo Dulce,4.0,37.316788,-5.658764,Sevilla,Carmona,noble estate,Marqués de Saltillo,pine
181,1749,Chaparral,Chaparral,87.0,37.519055,-6.235116,Sevilla,Aznalcóllar,comunal,Aznalcóllar,holm oak
90,1748-1749,Dehesa de Purchena,Dehesa de Purchena,170.0,37.355840,-6.438209,Huelva,Villalba del Alcor,noble estate,Marqués de Priego,holm oak
...,...,...,...,...,...,...,...,...,...,...,...
351,1749-1751,Utrera,Utrera,1.0,0.000000,0.000000,Sevilla,Utrera,private,Luis Antonio Cabrera,pine
173,1749,Genis,Hacienda de Genis,56.0,37.359515,-6.360745,Huelva,Chucena,noble estate,Marqués de Las Torres,pine
9,1748-1749,Chorreadero,Chorreadero,370.0,36.834277,-5.517623,Cádiz,Zahara de la Sierra,undefined,undefined,undefined species
412,1751,Dehesa de Gato,El Gato,8.0,37.245663,-6.343690,Sevilla,Villamanrique de la Condesa,noble estate,Marquesa de Astorga,holm oak
54,1749-1750,Cavezadas del Guadarranque,Río Guardarranque,30.0,36.382793,-5.538237,Málaga,Cortes de la Frontera,comunal,Cortes de la Frontera,"holm oak, gall oak"

In [ ]:
df_final = df_final[
    [
        'felling_period',
        'felling_toponymy_source',
        'felling_toponymy_MTN25',
        'latitude',
        'longitude',
        'province',
        'municipality',
        'landownership',
        'landowner_name',
        'tree_species',
        'tree_quantity'
    ]
]

In [ ]:
df_final.head()

,felling_period,felling_toponymy_source,felling_toponymy_MTN25,latitude,longitude,province,municipality,landownership,landowner_name,tree_species,tree_quantity
0,1748-1749,Benahú,Dehesa de Benahú,36.576893,-5.509202,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak,622.0
1,1748-1749,Jarda,Dehesa de la Jarda,36.602238,-5.601913,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak,230.0
2,1748-1749,Barranco de la Fantasma,La Fantasma,36.609978,-5.464804,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak,240.0
3,1748-1749,La Jardilla,La Jardilla,36.621789,-5.518366,Cádiz,Jerez de la Frontera,comunal,Jerez de la Frontera,gall oak,1457.0
4,1748-1749,Garganta de Millán,Millán,36.616171,-5.474945,Cádiz,Jerez de la Frontera,undefined,undefined,gall oak,250.0

In [ ]:
df_final.to_csv('../data/cleaned/dataset_maderas_final.csv', index=False)

In [ ]:
df_final.isna().sum()

felling_period             0
felling_toponymy_source    0
felling_toponymy_MTN25     0
latitude                   0
longitude                  0
province                   0
municipality               0
landownership              0
landowner_name             0
tree_species               0
tree_quantity              0
dtype: int64

In [ ]:
df_final[df_final.isna().any(axis=1)]

Empty DataFrame
Columns: [felling_period, felling_toponymy_source, felling_toponymy_MTN25, latitude, longitude, province, municipality, landownership, landowner_name, tree_species, tree_quantity]
Index: []